"""Modul „Gegenstimmen: Mainz im Genusse der Freiheit und Gleichheit“ (Flugschrift, 1793).

Quelle: Mainz im Genusse der durch die Franzosen errungenen Freiheit und Gleichheit, oder die Leiden der treuen mainzer
Bürger unter dem Joche der Franzosen und Klubbisten, mit einem Anhange aller während dieser Zeit in Mainz
herausgekommenen Proklamationen ([o. O.]: „Deutschland“ 1793), S. 6–9, 17–23, 25–28.
Gelesen an den Seitenbildern der Bayerischen Staatsbibliothek, bsb11779263 (Bildnummer = Seite + 12).
Schreibung des Drucks; ſ als s; Silbentrennung aufgelöst; Kustoden weggelassen. Auslassungen […].
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "gegenschrift.json"


def u(n, pg, titel, titel_en, orig, en, note="", note_en=""):
    d = {"n": n, "pg": pg, "titel": titel, "titel_en": titel_en, "orig": orig.strip(), "en": en.strip()}
    if note:
        d["note"], d["note_en"] = note, note_en
    return d


STIMMUNG = [
    u(1, "Titel", "Das Titelblatt", "The title page",
      """Mainz im Genusse der durch die Franzosen errungenen Freiheit und Gleichheit, oder die Leiden der treuen mainzer Bürger unter dem Joche der Franzosen und Klubbisten mit einem Anhange aller während dieser Zeit in Mainz herausgekommenen Proklamationen.
Deutschland, 1793.""",
      """Mainz in the Enjoyment of the Liberty and Equality Won by the French, or the Sufferings of the Loyal Citizens of Mainz under the Yoke of the French and the Clubists, with an appendix of all the proclamations issued in Mainz during this time.
Germany, 1793.""",
      "Die Flugschrift erschien ohne Verfasser und mit dem Druckort „Deutschland“. In der Vorrede sprechen „die Verfasser“, im Plural, und wollen die Zeit „unsern Nachkommen“ überliefern. Sie schreiben im Ton des Hohns, aber, anders als Hoffmann, als Gemäßigte, die eine Verfassungsreform aus eigener Kraft gewollt hätten ([2]).",
      "The pamphlet appeared without an author and with the place of printing 'Germany'. In the preface 'the authors' speak in the plural and wish to hand the time down 'to our descendants'. They write in a tone of scorn, but, unlike Hoffmann, as moderates who would have wanted constitutional reform by their own strength ([2])."),
    u(2, "6–7", "„Ohne alle Explosion“", "'Without any explosion'",
      """[…] auf Uns passe, — daß es ein Unglück wäre, wenn Franken zu Uns kämen, um Uns diese Constitution zu geben, wenn Wir Uns nicht nach Unserm eigenen Maaßstabe ohne alle Explosion, durch keine andere Triebfeder, als fortschreitende Aufklärung, lebendigern Antheil an gegenseitigen Leiden, bessere Erziehung, geläuterte Moralität, Einschränkung des Luxus organisirten; sie wurden aber von den andern, die nichts als höchste irrdische Seligkeit wähnten, überschrien und so — schienen sich — gemäßigte und — ekstatische Köpfe unter einen Huth — zu werfen.
Unter allen Ständen in Mainz, war Abneigung gegen die französische Constitution, bey jenen allgemein, die aus kaltblütiger Erfahrung, aus ganz einfachen Raisonnements berechneten, daß Deutsche — nie durch Franzosen glücklich gemacht werden können, am wenigsten, wenn dies Glück durch Uebermacht der Waffen installirt und behauptet werden sollte. Von einer so eitlen Nation, die auf den Deutschen, wie auf ein unbelebtes Erdkloß, herabsah, nichts, als verstellte, in leeren Worten ausgekramte, nur so lange daurende Zuneigung und gute Begegnung erwarten, bis sie, im Besitze des Landes, sich um keine Rücksichten mehr zu kümmern, sondern ihrer Verachtung den vollen Lauf lassen konnte, schien ihnen eben so natürlich, als die Mittel, wodurch diese Glückseligkeit verbreitet werden sollte, ihnen höchst unnatürlich, unausführbar, auf Maynz gar nicht passend, und keinesweges das Resultat der Menschenliebe, vielmehr Wirkungen des unbändigsten Ehrgeitzes, des ausschließendesten Egoismus, vorkamen. — In der Ferne sahen sie die unausbleiblichen Folgen, die Rüstungen aller Mächte, die unbedingte Unmöglichkeit, französisch zu bleiben — und die gewaltsamen Mittel, zu denen jeder Theil seine Zuflucht nehmen würde, — der eine, es zu behaupten, der andere, es wieder zu entreißen — Mittel, unter denen Maynz allemal am meisten leiden würde.""",
      """[…] suited Us — that it would be a misfortune if Franks came to Us to give Us this constitution, unless We organized Ourselves by Our own measure, without any explosion, by no other motive than advancing enlightenment, livelier sympathy for one another's sufferings, better education, purified morals and restraint of luxury; but they were shouted down by the others, who imagined nothing but the highest earthly bliss, and so — moderate and — ecstatic heads seemed — to throw themselves under one hat.
Among all the estates in Mainz there was aversion to the French constitution, general among those who calculated from cool-headed experience and quite simple reasoning that Germans — can never be made happy by Frenchmen, least of all if this happiness was to be installed and maintained by superior force of arms. From so vain a nation, which looked down on the German as on a lifeless clod of earth, to expect nothing but feigned affection and good treatment, displayed in empty words and lasting only until, in possession of the land, it could stop caring for any consideration and give free rein to its contempt, seemed to them as natural as the means by which this happiness was to be spread seemed to them most unnatural, impracticable, not at all suited to Mainz, and in no way the result of love of mankind, but rather the effects of the most unbridled ambition and the most exclusive egoism. — In the distance they saw the inevitable consequences, the armaments of all the powers, the absolute impossibility of remaining French — and the violent means to which each side would resort, — the one to keep it, the other to tear it back — means under which Mainz would always suffer most.""",
      "Der Kern der gemäßigten Gegenstimme: nicht gegen Reformen, sondern gegen Reformen durch fremde Waffen. Der letzte Satz sagt die Belagerung voraus, die Forster für ausgeschlossen hielt (Forster [18]): Mainz werde zwischen beiden Seiten „allemal am meisten leiden“. Die Großschreibung „Uns“, „Wir“ steht so im Druck.",
      "The core of the moderate counter-voice: not against reforms, but against reforms by foreign arms. The last sentence foresees the siege that Forster thought out of the question (Forster [18]): Mainz would 'always suffer most' between the two sides. The capitalized 'Us', 'We' stand so in the print."),
    u(3, "7–9", "Landmann und Stadt: „schüchtern, ängstlich, betroffen“", "Countryman and city: 'timid, anxious, dismayed'",
      """Den Landmann konnte nichts unwiderstehlicher verführen, als die versprochene Befreyung von Steuern, Abgaben und Zehenten. Nichts mehr bezahlen, war bey den Meisten der höchste Grad von Freyheit, den sie sich denken konnten, und zugleich — der höchste Grad von Glückseligkeit. […] Und doch — war der Haufen nicht so groß, als man ihn nach diesen Verhältnissen hätte vermuthen sollen. Nur die Unvermögendsten, Unthätigsten, Unruhigsten, oder Hochmüthigsten sehnten sich nach den Franzosen; der größere Theil sah ein, daß jede Erleichterung, die er in Rücksicht auf die, in Wahrheit nicht schweren und mit keinen in der ganzen Nachbarschaft zu vergleichenden, Lasten erwarten konnte, durch alle damit verbundenen Gefahren, durch alles, was dabey erwartet würde, durch Ungewißheit, wie lange dieser neue Zustand, — durch die überwiegende Wahrscheinlichkeit, daß Derselbe nicht lange dauren könne — viel zu theuer erkauft sey. Schüchtern, ängstlich, betroffen harrte er in der Stille, und seufzte zum Himmel, daß er diese Landplage abwenden möge.
In diesem Gemische hyperbatischer, egoistischer, ehrsüchtiger, zügelloser, ängstlicher, furchtsamer, bedenklicher Erwartungen zogen die Franken ein; schon vor ihrem Einzuge prangte die Nationalkokarde auf den Hüten ihrer getreuen Correspondenten, und nun — wurde sie allgemein, mußte sie allgemein werden, theils der Mode, theils der Sicherheit vor Beschimpfungen, die man sich sonst, als Aristokrat, zuzog, wegen. […] Uebrigens hatte es so wenig Begriff von Freyheit, daß es vor — Custine zitterte.""",
      """Nothing could seduce the countryman more irresistibly than the promised freedom from taxes, dues and tithes. To pay nothing more was for most the highest degree of freedom they could imagine, and at the same time — the highest degree of happiness. […] And yet — the crowd was not so large as one would have expected from these circumstances. Only the poorest, idlest, most restless or most arrogant longed for the French; the greater part saw that any relief it could expect from burdens which were in truth not heavy and not comparable to any in the whole neighbourhood was bought far too dear by all the dangers bound up with it, by everything that would be expected in return, by the uncertainty of how long this new state would last — by the overwhelming probability that it could not last long. Timid, anxious, dismayed, it waited in silence and sighed to heaven that it might avert this scourge.
Amid this mixture of hyperbolic, egoistic, ambitious, unbridled, anxious, fearful, doubtful expectations the Franks marched in; even before their entry the national cockade adorned the hats of their faithful correspondents, and now — it became general, had to become general, partly from fashion, partly for safety from the insults one otherwise incurred as an aristocrat. […] For the rest it had so little notion of freedom that it trembled before — Custine.""",
      "Hier spricht die Gegenseite über das, was Caroline am Bauern bemerkte (Caroline [3]): Die Flugschrift nennt die Lasten im Kurstaat „in Wahrheit nicht schwer“. Wer recht hatte, entscheiden die beiden Texte nicht. Die Kokarde als Schutz vor dem Vorwurf, „Aristokrat“ zu sein, beschreibt auch Hoffmann (Custine [15]).",
      "Here the other side speaks of what Caroline observed in the peasant (Caroline [3]): the pamphlet calls the burdens in the Electorate 'in truth not heavy'. These two texts do not decide who was right. The cockade as protection against being called an 'aristocrat' is described by Hoffmann too (Custine [15])."),
]

HANDELSSTAND = [
    u(4, "17–19", "Der Vorschlag des Handelsstandes: 81 gegen 13", "The merchant estate's proposal: 81 to 13",
      """Der Handelsstand glaubte sich ebenfalls berufen, seine Heilungskraft zu versuchen. Nach einem Eingange, der durch den, dem General Küstine und der französischen Nation gestreuten Weyhrauch, durch Verdemüthigungen, die uns nie weniger, als in diesem Augenblicke zweckmäßig schienen, jeden biedern, sich seines Werthes bewußten, Deutschen etwas unangenehm überrascht, begehrte derselbe mit einer Majorität von 81 Stimmen gegen 13, welche sich für die französische Constitution erklärten, — Repräsentanten einzig aus den Gliedern der Bürgerschaft und Vornehmern des Landes gewählt, um dem Fürsten, der in allen wichtigen Angelegenheiten von der Nation abhängen müsse, und nicht willkührlich über das Vermögen des Bürgers, über die Einkünfte des Staates schalten dürfe, das Gleichgewicht zu halten. Kein Auswärtiger solle je zu einer Stelle, Würde, oder Beneficium gelangen können, die wichtigsten Stellen nicht anders, als durch die Wahl der Nation vergeben werden können. Neue Wahl der Repräsentanten alle zwey Jahre, eine die Gleichheit aller Bürger zum Grunde legende genaue Vertheilung aller Abgaben, Abschaffung aller mit Unrecht erhaltenen Privilegien der Geistlichkeit und des Adels, Vorbehalt, daß diese neue Konstitution in die Friedensartikel aufgenommen, durch Frankreich geschützet, vom Kaiser und deutschen Reiche anerkannt werde, beschließen diese Artikel. Von dem Verfasser, Dümont, waren diese Vorschläge wenigstens gut gemeint, und wären mit Dank anzunehmen gewesen, allein die Ausschließung der Ausländer von dem Landesstellen, wirkte wie ein Stich in ein Wespennest. Der Klub, oder die Gesellschaft der Constitutionsfreunde, an deren Spitze sich gerade diese Ausländer, diese von dem Kurfürsten mit Wohlthaten überhäuften Ausländer ganz vorsätzlich, stellten, um in der Mitte alle dieser Unruhen und Umwälzungen als Schriftsteller, Schöpfer der Freyheit, Lehrer des Volkes, Fabrikanten und Armenväter die Stellen zu behaupten, welche sie durch pralerische Versprechungen eines Nutzens, den sie nie leisteten, — so treflich sich anzumaßen wußten.""",
      """The merchant estate too believed itself called upon to try its healing power. After an opening which, by the incense strewn before General Custine and the French nation and by humiliations that never seemed to us less fitting than at that moment, somewhat unpleasantly surprised every honest German conscious of his worth, it demanded, by a majority of 81 votes against 13 who declared for the French constitution, — representatives chosen solely from the members of the citizenry and the notables of the land, to keep the balance against the prince, who must depend on the nation in all important matters and may not dispose arbitrarily of the citizen's property and the revenues of the state. No foreigner should ever be able to obtain an office, dignity or benefice; the most important offices should be given only by election of the nation. New election of the representatives every two years, an exact distribution of all taxes based on the equality of all citizens, abolition of all wrongly obtained privileges of the clergy and the nobility, and the reservation that this new constitution be included in the articles of peace, protected by France and recognized by the Emperor and the German Empire, conclude these articles. These proposals were at least well meant by their author, Dumont, and would have deserved to be accepted with thanks; but the exclusion of foreigners from the offices of the land worked like a jab into a wasps' nest. The club, or the Society of the Friends of the Constitution, at whose head precisely these foreigners, these foreigners loaded with benefits by the Elector, quite deliberately placed themselves, in order, in the midst of all this unrest and upheaval, to secure for themselves as writers, creators of freedom, teachers of the people, manufacturers and fathers of the poor the posts which they had so cleverly usurped by boastful promises of a usefulness they never provided.""",
      "Die Gegenseite zu Forsters Rede: Das ist der „Handelsständische Vorschlag“, das „Mittelding“ mit Wahlfürst und Landständen, gegen das Forster im November sprach (Forster [25]; Forster [32]). Er stammte nach dieser Schrift von Daniel Dumont, dem Kaufmann, der im Februar 1793 die Erklärung der Bürger verfasste und dafür ausgewiesen wurde (Eid [22]). Die Spitze gegen die „Ausländer“ zielt auf Forster selbst, der kein Mainzer war (Forster [14]).",
      "The other side of Forster's speech: this is the 'proposal of the merchant estate', the 'middle thing' with an elected prince and estates that Forster spoke against in November (Forster [25]; Forster [32]). According to this pamphlet it came from Daniel Dumont, the merchant who drafted the citizens' declaration in February 1793 and was expelled for it (Eid [22]). The jab at the 'foreigners' is aimed at Forster himself, who was not from Mainz (Forster [14])."),
]

BOEHMER = [
    u(5, "20–21", "„Deinen Kopf oder Musik!“", "'Your head or music!'",
      """Einem gesetzlosen Menschen, wie Böhmern, der sich so weit vergaß, daß er dem Schultheissen von Laubenheim, der seinen Bauern aus ganz guten, auf ihre Lage passenden Gründen die Haltung der Musik an einem gewissen Tage abgeschlagen hatte, auf gut sultanisch zuschrieb: Schultheiß von Laubenheim! Deinen Kopf oder Musik! — — einem solchen Menschen mußte nichts unverdaulicher seyn, als, die zeitherigen Stellen in den geringen Ueberbleibseln ihres Ansehens beybehalten und hiedurch dem Strohme alles Unfuges, den er losließ, einen schwachen Damm gesetzt zu sehen. Sie also verächtlich und klein machen, war das einzige, was ihm übrig blieb, und, was er unverschämt genug, unter dem Titel: Warnung, als ein bloß in seinem Nahmen erlassenes, von ihm allein unterschriebenes Edikt der Nationalzeitung folgenden Inhaltes, das allerdings als ein Monument dieser Zeit Wort für Wort aufbewahrt zu werden verdient, einrückte:""",
      """For a lawless man like Böhmer, who forgot himself so far as to write, quite in the manner of a sultan, to the mayor of Laubenheim, who for very good reasons suited to their situation had refused his peasants leave to hold music on a certain day: Mayor of Laubenheim! Your head or music! — — for such a man nothing could be harder to stomach than to see the existing offices kept in the slight remnants of their authority and thus a weak dam set against the flood of all the mischief he let loose. To make them contemptible and small was therefore the only thing left to him, and this he did, shamelessly enough, under the title 'Warning', as an edict issued solely in his own name and signed by him alone, which he inserted in the National Newspaper with the following content, which indeed deserves to be preserved word for word as a monument of this time:""",
      "Laubenheim ist ein Weinort südlich von Mainz. „Musik“ heißt hier wohl: ein Fest mit Tanz. Georg Wilhelm Böhmer, Custines Sekretär, war Carolines Schwager (Caroline [2]).",
      "Laubenheim is a wine village south of Mainz. 'Music' here probably means a festivity with dancing. Georg Wilhelm Böhmer, Custine's secretary, was Caroline's brother-in-law (Caroline [2])."),
    u(6, "21–23", "Böhmers „Warnung“ (11. November 1792)", "Böhmer's 'Warning' (11 November 1792)",
      """Warnung.
„Da bekanntlich die Stadt und ein ansehnlicher Theil des ehemaligen Kurfürstenthumes Mainz itzt in den Händen der Franken ist; — da nur die, der fränkischen Nation ganz eigene Großmuth, die bisher konstituirten Gewalten einsweilen beibehalten hat; da endlich der Bürger, General Küstine, es sämtlichen Regierungsräthen, Amtleuten u. s. w. ausdrücklich zur Pflicht gemacht hat, sich provisorisch beybehaltene rc. zu unterschreiben, so ist es in der That auffallend, wenn Beamte dieses Landes noch schwach genug sind, sich als kurfürstlich mainzische Beamte zu unterzeichnen, gleich als ob es mehr Ehre wäre, einem flüchtigen Miethlinge, als einem souverainen Volke zu dienen! —“
„Diesesmal werden die Herren noch brüderlich gewarnet. Ist dieses umsonst, so wird man ihre Nahmen der öffentlichen Verachtung Preis geben.“
„Noch ist zu bemerken, daß man dem guten mainzer Bürger und Landmanne durch allerley aristokratische Mittel zu überreden gesucht hat, es wäre Wille des edlen Küstine, Wille der erhabenen Frankennation, daß die Regierung völlig und beständig so fort dauern solle, wie sie leider! bisher bestanden ist. Die Proklamationen des genannten Generals reden ganz anders. Nur so lange sollen die bisher konstituirten Gewalten unterstützet werden, bis das Volk sich freywillig durch Mehrheit der Stimmen erklärt hat, ob es seine bisherigen Fesseln tragen oder frey seyn und sich seine Obern selbst wählen will. Welche von beyden Parthien ein schwer gedrücktes Volk ergreifen werde, läßt sich sehr leicht vorher sehen. Und denn gute Nacht, Herr Amtmann! gute Nacht, Herr Amtsvogt u. s. w. Waret ihr brav, dientet ihr uneigennützig, so wird euch das Volk wieder wählen. Waret ihr aber ungerecht, verkauftet ihr die Gerechtigkeit an die Meistbiethenden, saht ihr die Person an, statt das Recht anzusehen, mit einem Worte, zeigtet ihr euch nicht als Schutz- sondern als Würgengel eurer Brüder — dann, o dann lernt erst fühlen, was Menschenelend ist, macht euch mit den Mitteln bekannt, es zu mindern, ehe ihr euch je wieder Hofnung macht vom Volke, das ihr bis dahin verschmähtet, auch nur zu einem kleinen Dienste gewählt zu werden.
Mainz, den 11ten Novbr. 1792. im ersten Jahre der Republik.
Georg Wilhelm Böhmer.“
Dies impertinente Produkt dieses Küstinischen Miethlinges machte unter dem Volke, in Rücksicht auf eine neue Verfassung, um so weniger Sensation, als es schon damal ohne alles Zuthun aristokratischer Mittel gerade durch solche und ähnliche Erscheinungen gestimmet war, hundertmal eher seine vorige Konstitution, als die ihm dargebothene, anzunehmen.""",
      """Warning.
'Since, as is well known, the city and a considerable part of the former Electorate of Mainz are now in the hands of the Franks; — since only the magnanimity peculiar to the Frankish nation has provisionally retained the authorities constituted so far; since, finally, Citizen General Custine has expressly made it the duty of all government councillors, bailiffs etc. to sign themselves "provisionally retained" etc., it is indeed striking when officials of this land are still weak enough to sign themselves as Electoral Mainz officials, as though it were more honourable to serve a fugitive hireling than a sovereign people! —'
'This time the gentlemen are still warned in brotherly fashion. If this is in vain, their names will be given over to public contempt.'
'It should further be noted that the good citizen and countryman of Mainz has been persuaded by all kinds of aristocratic means that it was the will of the noble Custine, the will of the sublime Frankish nation, that the government should continue completely and permanently as it has, alas, existed until now. The general's proclamations say something quite different. The constituted authorities are to be supported only until the people has declared freely by a majority of votes whether it will bear its former fetters or be free and elect its superiors itself. Which of the two parties a heavily oppressed people will take is very easy to foresee. And then good night, Mr Bailiff! good night, Mr Steward, etc. If you were honest and served unselfishly, the people will elect you again. But if you were unjust, sold justice to the highest bidder, looked at the person instead of at the law — in a word, if you showed yourselves not as guardian angels but as destroying angels of your brothers — then, oh then, first learn to feel what human misery is, acquaint yourselves with the means of lessening it, before you ever again hope to be elected by the people, which you scorned until then, even to the smallest service.
Mainz, 11 Nov. 1792, in the first year of the Republic.
Georg Wilhelm Böhmer.'
This impertinent product of Custine's hireling made all the less sensation among the people with regard to a new constitution, since even then, without any help from aristocratic means, it was disposed by precisely such and similar appearances to accept its former constitution a hundred times sooner than the one offered to it.""",
      "Ein Dokument der Klubseite, von ihren Gegnern vollständig abgedruckt, damit es sich selbst widerlege. Böhmer setzt auf eine freie Mehrheitsentscheidung, deren Ausgang er „sehr leicht vorher sehen“ kann. Drei Monate später durfte nur abstimmen, wer schwor (Eid [2]). Die „Nationalzeitung“ ist die Mainzer Zeitung, die Böhmer herausgab.",
      "A document of the club's side, printed in full by its opponents so that it would refute itself. Böhmer counts on a free majority decision whose outcome he can 'very easily foresee'. Three months later only those who swore were allowed to vote (Eid [2]). The 'National Newspaper' is the Mainz newspaper that Böhmer edited."),
    u(7, "25", "Custine und die Beamten", "Custine and the officials",
      """[…] ein Despot, wie Küstine, dessen hochtrabender Ton und Tiranney dem Regimente Saintonge, welches er in Amerika kommandirte, ewig unvergeßlich seyn wird, ist gar keiner Gründe empfänglich, er droht, dieser große Freyheitsfreund, und wehe dem, der nicht niederfällt! er wirft ihn alsdenn seinen Hunden Stamm, Cotta, Maier, seiner Legion, dem Klub vor, wo er brüderlich zerrissen oder nach besserer Form Rechtens dem Galgen zugedacht wird. — Den Stellen, die keinen Wink, keine Silbe vom Kurfürsten hörten, die sich selbst und der Wuth aller jener, welche nach ihrer Auflösung, nach ihrer Verbannung schnaubten, überlassen, nicht mehr wußten, was sie retten sollten, blieb nichts anders übrig, als dem Doktor Böhmer die Unbilligkeit dieser Zumuthung vorzustellen, und, nachdem dieser, seines Sultans so würdige Pascha, ihnen den Schaum seines allgewaltigen Grimmes beynahe ins Gesicht gespien hatte — zu gehorchen.""",
      """[…] a despot like Custine, whose high-flown tone and tyranny the Saintonge regiment, which he commanded in America, will never forget, is not open to any reasons at all; he threatens, this great friend of freedom, and woe to him who does not fall down! he then throws him to his dogs Stamm, Cotta, Maier, his legion, the club, where he is torn to pieces in brotherly fashion or, in better legal form, destined for the gallows. — The government offices, which heard no hint, not a syllable from the Elector, left to themselves and to the fury of all those who snorted for their dissolution and banishment, no longer knew what to save; nothing was left to them but to represent to Doctor Böhmer the unfairness of this demand and, after this pasha so worthy of his sultan had nearly spat the foam of his almighty wrath in their faces — to obey.""",
      "Custine hatte im amerikanischen Unabhängigkeitskrieg das Regiment Saintonge geführt. Stamm, Cotta und Maier waren zugewanderte Klubisten, also eben jene „Ausländer“, gegen die sich die Flugschrift wendet ([4]). Bemerkenswert ist der Vorwurf an den Kurfürsten: Die Beamten hörten von ihm „keinen Wink, keine Silbe“.",
      "Custine had commanded the Saintonge regiment in the American War of Independence. Stamm, Cotta and Maier were Clubists who had come from elsewhere, the very 'foreigners' the pamphlet turns against ([4]). The reproach to the Elector is remarkable: the officials heard from him 'no hint, not a syllable'."),
]

BUECHER = [
    u(8, "26–27", "Das Buch des Lebens und das Buch des Todes", "The Book of Life and the Book of Death",
      """[…] ihm verdankt man den herrlichen Einfall des rothen und schwarzen Buchs — herrlich, weil diese ihres Urhebers würdige Erfindung wesentliche Dienste manchem, mit Blindheit Geschlagenen geleistet und ihm den vollen Gebrauch seines Gesichtes wiedergegeben hat.
Das in rothem Saffian gebundene Buch, sonst auch Buch des Lebens genannt, geziert mit der Freyheitsmütze, und am Rande mit den Nationalfarben, enthielt im Eingange den dem Volke, als höchster Gewalt, geleisteten Huldigungseid, Erkenntniß der Freyheit und Gleichheit, Annahme der hierauf gegründeten fränkischen Konstitution.
Das in schwarzes Papier gebundene, mit Ketten umwundene Buch, welches man im Gegensatze mit jenem, das Buch des Todes hätte nennen sollen, hatte blos die Ueberschrift: Sklaverey.
Höflich wurden sämtliche männlichen Bürger und Einwohner der mainzer Stadt und Gegend von 21 Jahren an ersucht, sich entweder das eine oder das andere dieser Bücher zu wählen, um ihre Namen zu unterschreiben, indem es schlechterdings nothwendig ist, hieß es, daß der Bürger Kustine wisse, wie er daran ist.
Nach Bestimmung der Stunden zur Unterschrift schloß Böhmer ganz im Geiste der Freyheit und Gleichheit: „Wer gar nicht erscheinet, erklärt sich stillschweigend für einen Freund der alten Sklaverey, und hat sich hernach selbst zuzuschreiben, wenn er, wie ein Sklave, behandelt wird —! —!“
Sehen mußte man sie die Bestürzung, welche diese unüberlegte Auffoderung verursachte. In vollem Schrecken, und, ohne zu wissen, was sie thaten, eilten viele guten, redlichen, ruhigen Menschen, ihre Namen in das rothe Buch einzuschreiben; in den ersten Tagen fühlten sie sich erleichtert, in den folgenden geängstiget, durch alles, was ihnen dieser Schritt zuziehen konnte. Mistrauisch auf jeden, welchen sie um Rath zu fragen dachten, irrten viele umher, in ähnlicher Lage diejenigen, welche Rath geben sollten; eine Art von Verzweifelung, von panischer Furcht, von Besorgniß, nach längerer Zögerung, aus dem Buche des Lebens ausgeschlossen zu seyn, trieb sie heerdenweise hin, sie unterschrieben und — bereueten noch in demselben Augenblicke, was sie gethan hatten.""",
      """[…] to him we owe the splendid idea of the red and the black book — splendid, because this invention, worthy of its author, rendered essential services to many a man struck with blindness and gave him back the full use of his sight.
The book bound in red morocco, otherwise also called the Book of Life, adorned with the cap of liberty and with the national colours along its edge, contained at its opening the oath of homage sworn to the people as the highest authority, the recognition of liberty and equality, and the acceptance of the Frankish constitution founded on them.
The book bound in black paper and wound about with chains, which by contrast with the other should have been called the Book of Death, bore only the heading: Slavery.
All male citizens and inhabitants of the city and region of Mainz from the age of 21 were politely requested to choose one or the other of these books in which to sign their names, since it was absolutely necessary, it was said, that Citizen Custine should know where he stood.
After fixing the hours for signing, Böhmer concluded, quite in the spirit of liberty and equality: 'Whoever does not appear at all declares himself tacitly a friend of the old slavery, and will have only himself to blame afterwards if he is treated as a slave —! —!'
One should have seen the dismay this rash summons caused. In utter terror, and without knowing what they were doing, many good, honest, quiet people hurried to write their names in the red book; in the first days they felt relieved, in the following ones frightened by everything this step might bring upon them. Distrustful of everyone they thought of asking for advice, many wandered about, and those who were to give advice were in a similar situation; a kind of despair, of panic fear, of anxiety at being shut out of the Book of Life after longer hesitation drove them there in herds; they signed and — regretted what they had done in the very same moment.""",
      "Dieselbe Szene wie bei Hoffmann (Forster [4]–[6]), mit einer Zutat: die Unterschreibenden, die es „noch in demselben Augenblicke“ bereuen. Die Drohung zitiert die Flugschrift wörtlich, Forster verteidigt sie in seiner Rede (Forster [28]).",
      "The same scene as in Hoffmann (Forster [4]–[6]), with an addition: the signers who regret it 'in the very same moment'. The pamphlet quotes the threat word for word; Forster defends it in his speech (Forster [28])."),
    u(9, "28", "Die Beamten und ihr Eid", "The officials and their oath",
      """Niemand war übler gesetzt, als die Dikasterien; dem Kurfürsten durch einen besondern Eid, den nur eine legale, keine usurpirte Macht aufheben konnte, verpflichtet, ohne Vorschrift, ohne Wink, konnten sie sich in das rothe Buch nicht einschreiben, oder, sie kompromittirten dies alles, und, was noch mehr ist, als dies alles, sie kompromittirten ihre Grundsätze, welche freyen Männern nicht erlauben, sich, auch nur bey dem Schatten eines Zwanges, wie viel weniger bey einer so schändlichen Drohung von Sklaverey! zu einer Handlung verleiten zu lassen, die das Herz abschwört. Ihre Unterschrift hätte ein Unding von Constitution, das noch gar nicht existirt, sanktionirt und vorläufig alles gebilligt, was bey seiner Erscheinung alle besseren Menschen einstimmig verworfen hätten. Indeß liefen sie aber auch bey einer längern Widersetzlichkeit Gefahr, als Aristokraten erklärt, gesteinigt, geplündert, mißhandelt zu werden. Läßt sich von dem einzelnen, der Welt durch keine Frau, durch keine Kinder zugehörenden Manne allenfalls dieser hohe Grad von Muth fodern, so scheint es Härte, das nämliche von dem Gatten […]""",
      """No one was in a worse position than the government offices: bound to the Elector by a special oath, which only a lawful power, not a usurped one, could lift, without instructions, without a hint, they could not sign the red book; otherwise they compromised all this, and, what is more than all this, they compromised their principles, which do not allow free men to be led, even at the shadow of compulsion, how much less under so shameful a threat of slavery! to an act that the heart forswears. Their signature would have sanctioned a monstrosity of a constitution that did not yet exist at all and approved in advance everything that all better men would unanimously have rejected when it appeared. Yet if they resisted longer, they also ran the danger of being declared aristocrats, stoned, plundered and mistreated. If this high degree of courage may perhaps be demanded of the single man, bound to the world by no wife and no children, it seems harsh to demand the same of the husband […]""",
      "Die Flugschrift beruft sich auf dasselbe, worauf sich die Revolution berief: auf freie Männer, die sich zu nichts zwingen lassen. Sie zeigt das Dilemma, das das Spiel abbilden soll: Ein Eid gegen den anderen, und keiner von beiden frei.",
      "The pamphlet appeals to the same thing the Revolution appealed to: free men who will not be compelled to anything. It shows the dilemma the game is meant to depict: one oath against another, and neither of them free."),
]

SECS = [
    ("stimmung", "Die Stimmung der Stadt", "The mood of the city", STIMMUNG,
     "Eine anonyme Mainzer Flugschrift von 1793 erzählt die Besatzung aus der Sicht gemäßigter Bürger: Reformen ja, aber nicht durch fremde Waffen; die meisten warteten „schüchtern, ängstlich, betroffen“.",
     "An anonymous Mainz pamphlet of 1793 tells the occupation from the point of view of moderate citizens: reforms yes, but not by foreign arms; most people waited 'timid, anxious, dismayed'."),
    ("handelsstand", "Der Vorschlag der Kaufleute", "The merchants' proposal", HANDELSSTAND,
     "Mit 81 gegen 13 Stimmen verlangt der Handelsstand eine eigene Verfassung mit gewählten Repräsentanten, ohne Ausländer in den Ämtern, garantiert von Frankreich, Kaiser und Reich: der Vorschlag, gegen den Forster sprach.",
     "By 81 votes to 13 the merchant estate demands a constitution of its own with elected representatives, no foreigners in office, guaranteed by France, Emperor and Empire: the proposal Forster spoke against."),
    ("boehmer", "Böhmers Warnung", "Böhmer's warning", BOEHMER,
     "Georg Wilhelm Böhmer, Custines Sekretär, droht den kurfürstlichen Beamten öffentlicher Verachtung, wenn sie sich weiter „kurfürstlich“ unterzeichnen. Die Flugschrift druckt seine „Warnung“ vollständig ab.",
     "Georg Wilhelm Böhmer, Custine's secretary, threatens the Elector's officials with public contempt if they go on signing themselves 'Electoral'. The pamphlet prints his 'Warning' in full."),
    ("buecher", "Die zwei Bücher", "The two books", BUECHER,
     "Das „Buch des Lebens“ und das „Buch des Todes“ aus der Sicht derer, die unterschreiben mussten, und der Beamten, die durch einen Eid an den Kurfürsten gebunden waren.",
     "The 'Book of Life' and the 'Book of Death' from the point of view of those who had to sign, and of the officials bound by an oath to the Elector."),
]

DATA = {
    "titel": "Gegenstimmen: „Mainz im Genusse der Freiheit und Gleichheit“ (1793)",
    "titel_en": "Voices against: 'Mainz in the Enjoyment of Liberty and Equality' (1793)",
    "autor": "Anonyme Mainzer Verfasser",
    "autor_en": "Anonymous authors from Mainz",
    "jahr": "1793",
    "sprache": "de",
    "orig_sprache": "de",
    "pg_label": "S.",
    "quelle": "Mainz im Genusse der durch die Franzosen errungenen Freiheit und Gleichheit, oder die Leiden der treuen mainzer Bürger unter dem Joche der Franzosen und Klubbisten, mit einem Anhange aller während dieser Zeit in Mainz herausgekommenen Proklamationen ([o. O.]: „Deutschland“ 1793), S. 6–9, 17–23, 25–28. Gelesen am Digitalisat der Bayerischen Staatsbibliothek München (bsb11779263).",
    "hinweis": "Eine anonyme Flugschrift aus dem Jahr der Belagerung, geschrieben von Mainzern, die die französische Verfassung ablehnten, aber nicht jede Reform. Sie ist polemisch und parteiisch wie Hoffmann, doch aus einem anderen Lager: dem der gemäßigten Bürger und Kaufleute. Ihr Anhang enthält die Proklamationen der Besatzungszeit; hier sind nur Auszüge des erzählenden Teils abgedruckt. Text nach dem Druck, an den Seitenbildern gelesen; Auslassungen sind mit […] bezeichnet. Die englische Übersetzung ist eine eigene Arbeitsübersetzung (CC0).",
    "hinweis_en": "An anonymous pamphlet from the year of the siege, written by people of Mainz who rejected the French constitution but not every reform. It is polemical and partisan like Hoffmann, but from another camp: that of the moderate citizens and merchants. Its appendix contains the proclamations of the occupation; only excerpts of the narrative part are printed here. Text as printed, read against the page images; omissions are marked […]. The English translation is my own working translation (CC0).",
    "sections": [{"id": i, "titel": t, "titel_en": te, "zk": "Gegenschrift", "blurb": b, "blurb_en": be, "units": us}
                 for i, t, te, us, b, be in SECS],
}

if __name__ == "__main__":
    ns = [x["n"] for s in DATA["sections"] for x in s["units"]]
    assert ns == list(range(1, len(ns) + 1)), ns
    OUT.write_text(json.dumps(DATA, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print("ok", OUT.name, len(ns), "units")
