"""Modul „Custine vor Mainz“: die Tage vom 7. bis 21. Oktober 1792 in Anton Hoffmanns Darstellung der Mainzer Revolution.

Quelle: [Anton Hoffmann], Darstellung der Mainzer Revolution, Heft 1 (Frankfurt und Leipzig 1793), Vorrede S. 1–2, 10;
Erzählung S. 58–59, 63–66; Beylagen No. 1–9, S. 67–80; dazu eine Anmerkung aus Heft 2, S. 156.
Gelesen an den Seitenbildern der Bayerischen Staatsbibliothek (bsb10421482, bsb10421483; Bildnummer = Seite + 2 in Heft 1,
Seite − 78 in Heft 2). Schreibung des Drucks; ſ als s, Umlaute wie gedruckt, Kustoden weggelassen.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "custine.json"


def u(n, pg, titel, titel_en, orig, en, note="", note_en=""):
    d = {"n": n, "pg": pg, "titel": titel, "titel_en": titel_en, "orig": orig.strip(), "en": en.strip()}
    if note:
        d["note"], d["note_en"] = note, note_en
    return d


STATTHALTER = [
    u(1, "67–70", "No. 1. Proklamation an die Bürger der Stadt Mainz (7. Oktober 1792)",
      "No. 1. Proclamation to the citizens of the city of Mainz (7 October 1792)",
      """Von der Kurfürstlichen Statthalterschaft wegen wird Namens seiner Kurfürstlichen Gnaden, unsers allerseits gnädigsten Herrn, hiermit bekannt gemacht:
Obgleich nach allen Völkerrechten nicht zu vermuthen stehet, daß die französische Nation ohne alle Kriegserklärung das Teutsche Reich feindlich behandlen, und die hiesige teutsche Reichsfestung, folglich mit ihr das ganze Reich anzugreifen gemeint seyn werde, so erfodert gleichwohl die Vorsicht, sich auf alle Fälle in den hinlänglichen Wehrstand zu setzen, und jeder unerwarteten Unternehmung mit teutschem Muth standhaft zu begegnen, um noch ferner die Ehre der Unerschrockenheit zu behaupten, wovon unsere brave Truppen noch jüngst ein so löbliches Beyspiel gegeben haben. Kurfürstliche Statthalterschaft hat bereits mit dem wärmsten Dankgefühle die rastlose Thätigkeit und den rühmlichen Biedersinn mit angesehen, womit die hiesige brave Bürgerschaft und sämmtliche rechtschaffene Einwohner zu den Waffen gegriffen haben: Nachdem es aber billig ist, daß auf den noch immer unverhoften Fall, wo von diesem tapfern Muth wirklicher Gebrauch gemacht werden müßte, auch für diejenigen gesorgt werde, welche sich vor andern der Gefahr ihres Lebens aussetzen, so verbindet sich hiemit die Kurfürstliche Statthalterschaft, Namens des gnädigsten Landesfürsten, daß im Falle ein streitender Bürger, oder Einwohner eine Verwundung erhalten würde, die ihn ausser Stand setzen möchte, eben so wie vorhin sein Brod zu gewinnen, derselbe jährlich aus dem Kurfürstlichen Aerario so lang er lebt, hundert Gulden zu genießen haben solle; würde er aber an der Folge seiner Wunden oder auf dem Platze sterben, so fallen diese 100 fl. seiner Frau und Kindern zu, und sie behalten solche, bis das jüngste Kind seine volle zwölf Jahre erreicht hat.
Sollte es ferner wieder alle Erwartung so weit kommen, daß Häuser in der Stadt in Brand geriethen, so wird die Hälfte des Schadens aus dem Kurfürstlichen Aerario bezahlt, die andere Hälfte aber nach der Gesellschaftsregel auf alle Einwohner und Häuserbesitzer der ganzen Stadt vertheilt werden, dergestalten, daß jeder einzelne Schaden nicht anders, als Schaden der ganzen Stadt ohne alle erdenkliche Ausnahme angesehen und behandelt werden solle. Endlich hat Kurfürstliche Statthalterschaft, um der hiesigen rechtschaffenen Bürgerschaft alle mögliche Hilfe zu verschaffen nicht nur zugleich, auch allen wehrhaften Landesunterthanen zur Hülfe aufgeboten, sondern auch sonst keine Mittel und Wege versäumt, um sich eines schleunigen äusserlichen Sukurses zu versichern.
Welches alles der hiesigen guten Stadt zu ihrem Trost, und jedem einzelnen Einwohner zu seiner Beruhigung hiermit bekannt gemacht wird Mainz den 7ten Oct. 1792.
Karl Georg Freyherr von Fechenbach Domdechant und Statthalter.
Franz Joseph Freyherr von Albini.""",
      """On behalf of the Electoral Lieutenancy, in the name of His Electoral Grace, our most gracious lord, it is hereby made known:
Although by all the law of nations it is not to be presumed that the French nation means to treat the German Empire as an enemy without any declaration of war, and to attack this German imperial fortress and with it the whole Empire, prudence nonetheless requires that we put ourselves in a sufficient state of defence against every eventuality and meet any unexpected undertaking steadfastly with German courage, so as to keep the honour of fearlessness of which our brave troops lately gave so praiseworthy an example. The Electoral Lieutenancy has already watched with the warmest gratitude the tireless activity and the commendable loyalty with which the brave citizenry here and all upright inhabitants have taken up arms. Since it is right, however, that in the still unexpected case where this brave courage had actually to be used, provision should also be made for those who expose their lives to danger before others, the Electoral Lieutenancy hereby binds itself, in the name of our most gracious sovereign, as follows: should a fighting citizen or inhabitant receive a wound that leaves him unable to earn his bread as before, he shall receive one hundred gulden a year from the Electoral treasury for as long as he lives; should he die of his wounds or on the spot, these 100 fl. shall go to his wife and children, and they shall keep them until the youngest child has reached the full age of twelve.
Should it further, against all expectation, come so far that houses in the city caught fire, half of the damage will be paid from the Electoral treasury, and the other half divided according to the rule of partnership among all the inhabitants and house-owners of the whole city, so that every single loss is regarded and treated as a loss of the whole city, without any exception whatever. Finally, to procure every possible help for the upright citizenry here, the Electoral Lieutenancy has not only called up all the able-bodied subjects of the land at the same time, but has also spared no means to secure speedy relief from outside.
All of which is hereby made known to this good city for its comfort and to every single inhabitant for his reassurance. Mainz, 7 Oct. 1792.
Karl Georg Freiherr von Fechenbach, cathedral dean and Lieutenant.
Franz Joseph Freiherr von Albini.""",
      "Der Kurfürst Friedrich Carl Joseph von Erthal war schon fort; die Statthalterschaft regierte in seinem Namen; Albini war Hofkanzler. „Reichsfestung“ ist umstritten: Hoffmann bestreitet den Titel in einer zweiten Anmerkung (S. 68), weil das Reich die Festung nie übernommen habe; Mainz sei Festung des Kurfürsten. Die Zusage für Verwundete und Brandschäden wurde nie eingelöst: Die Stadt ergab sich zwei Wochen später ohne Kampf.",
      "The Elector, Friedrich Carl Joseph von Erthal, had already gone; the Lieutenancy governed in his name; Albini was court chancellor. 'Imperial fortress' is contested: in a second note (p. 68) Hoffmann disputes the title, because the Empire never took the fortress over; Mainz was the Elector's fortress. The pledge for the wounded and for fire damage was never called on: the city surrendered two weeks later without a fight."),
    u(2, "67–68 Anm.", "Hoffmanns Anmerkung zur Proklamation", "Hoffmann's note on the proclamation",
      """Der Aufsetzer dieser Proklamation hatte wahrscheinlich vergessen, daß der Kurfürst von Mainz, ohne der französchen Nation den Krieg zu erklären, 2071 Mann seiner besten Truppen mit gehöriger Artillerie gegen die Franzosen nach Speier geschickt hatte; nach einem solchen Unternehmen erlaubet das Völkerrecht dem Gegentheil, ohne vorhergegangene Kriegserklärung seinen teutschen reichsständischen Feind feindlich zu behandlen, ohne daß ihm der Vorwurf gemacht werden könnte, er habe durch den Angriff dieses Feindes zugleich das teutsche Reich angegriffen, denn der Kurfürst von Mainz ist zwar ein Mitglied des teutschen Reiches, allein hier wird er nicht als ein solches, sondern als ein Alliirter des Königs von Böhmen und Ungarn angesehen, und von den Franzosen behandelt. Daß aber die Franzosen die Reichsstadt Speier und den Fürstbischof von Speier, der noch keinen Mann gegen die Franzosen in das Feld gestellet, und eben so wie der Landgraf von Hessendarmstadt durch die französische Nation gekränket worden war, angriffen und als Feind behandelten, dieses war gegen alles Völkerrecht und mußte einen Reichskrieg nothwendiger Weise nach sich ziehen.""",
      """The author of this proclamation had probably forgotten that the Elector of Mainz, without declaring war on the French nation, had sent 2,071 of his best troops with the proper artillery against the French at Speyer. After such an undertaking the law of nations allows the other side to treat its German enemy, an estate of the Empire, as an enemy without a prior declaration of war, and no one could reproach it with having attacked the German Empire by attacking this enemy; for the Elector of Mainz is indeed a member of the German Empire, but here he is regarded and treated by the French not as such but as an ally of the King of Bohemia and Hungary. That the French, however, attacked and treated as an enemy the imperial city of Speyer and the Prince-Bishop of Speyer, who had not yet put a single man into the field against the French and had been wronged by the French nation just as the Landgrave of Hesse-Darmstadt had been: that was against all the law of nations and was bound to draw an imperial war after it.""",
      "Hoffmann ist ein Gegner des Klubs, aber kein Hofschreiber: Hier wirft er der eigenen Regierung vor, die Lage zu beschönigen. Der „König von Böhmen und Ungarn“ ist Franz II., der im Juli 1792 zum Kaiser gekrönt worden war; Frankreich hatte im April 1792 ihm, nicht dem Reich, den Krieg erklärt. Bei Speyer wurden am 30. September 1792 die Mainzer und kaiserlichen Truppen geschlagen (Hoffmann, Heft 1, S. 18–20).",
      "Hoffmann is an opponent of the club, but no court writer: here he accuses his own government of glossing over the situation. The 'King of Bohemia and Hungary' is Francis II, crowned emperor in July 1792; in April 1792 France had declared war on him, not on the Empire. At Speyer on 30 September 1792 the Mainz and Imperial troops were beaten (Hoffmann, Heft 1, pp. 18–20)."),
    u(3, "70–71", "No. 2. An die Lesegesellschaft dahier (13. Oktober 1792)", "No. 2. To the reading society here (13 October 1792)",
      """Die bekannten dermaligen Zeitumstände würden zwar der Kurfürstlichen Statthalterschaft hinlängliche Ursache geben, alle französische Journalen und Zeitungsblätter, welche nichts als unglücklichen Aufruhr predigen, für die Zukunft zu verbieten; da jedoch K. Statthalterschaft vollkommen überzeugt ist, daß alle diese Schriften nicht vermögend sind, auf das dahiesige gutdenkende, und für seine eigne Ruhe rühmlich besorgte Publikum einen widrigen Eindruck zu machen, so gedenket zwar die K. Statthalterschaft noch zur Zeit nichts zu verfügen, was die Neugierde vieler hiesigen Einwohner beschränken könnte, Sie versiehet sich jedoch zu den Gliedern der Gesellschaft, daß dieselbe als patriotisch gesinnte Männer hievon keinen andern als nöthigen Gebrauch machen, und sich auf der Lesegesellschaft selbst bey Lesung solcher Schriften keine applaudirende Anmerkungen und Diskurse erlauben werden; indem Kurfürstl. Statthalterschaft, falls sie von einem oder dem andern Mitgliede dergleichen erfahren würde, eine solche Verwegenheit nicht anders als Zeichen eines, obgleich ohnmächtigen, doch bösen Willens ansehen, und mit aller Strenge andern Uebelgesinnten zum abschreckenden Beyspiel bestrafen müßte. Das Direktorium der Lesegesellschaft hat demnach diese Erinnerung in mehreren Abschriften auf dem Tische der Lesegesellschaft zu hinterlegen.
Mainz den 13ten October 1792.
Georg Carl Freyherr von Fechenbach Domdechant und Statthalter.
v. Albini.""",
      """The present circumstances, well known as they are, would indeed give the Electoral Lieutenancy sufficient cause to forbid for the future all French journals and newspapers, which preach nothing but unhappy rebellion. Since, however, the Electoral Lieutenancy is fully convinced that none of these writings is capable of making an adverse impression on the right-thinking public here, so laudably concerned for its own peace, the Electoral Lieutenancy does not for the present intend to decree anything that might restrict the curiosity of many inhabitants here. It trusts, however, that the members of the society, as patriotically minded men, will make no use of these papers but what is necessary, and will allow themselves no applauding remarks and discussions in the reading society itself when such writings are read; for should the Electoral Lieutenancy learn of anything of the kind from one member or another, it could not regard such audacity otherwise than as the sign of an ill will, impotent though it be, and would have to punish it with all severity as a deterrent example to other ill-disposed persons. The directorate of the reading society is accordingly to lay this reminder in several copies on the table of the reading society.
Mainz, 13 October 1792.
Georg Carl Freiherr von Fechenbach, cathedral dean and Lieutenant.
v. Albini.""",
      "Die Mainzer Lesegesellschaft war ein Verein gebildeter Bürger, Beamter und Professoren, die gemeinsam Zeitungen hielten. Viele spätere Klubisten waren Mitglieder. Die Regierung verbietet nicht das Lesen, sondern den Beifall. Zwei Unterschriften, zweimal anders: Am 7. Oktober „Karl Georg“, am 13. „Georg Carl“, beides wie gedruckt.",
      "The Mainz reading society was an association of educated citizens, officials and professors who took newspapers in common. Many later Clubists were members. The government forbids not reading but applause. Two signatures, spelled two ways: 'Karl Georg' on 7 October, 'Georg Carl' on the 13th, both as printed."),
]

AUFFORDERUNG = [
    u(4, "71–72", "No. 3. Erste Aufforderung des General Cüstine an den Gouverneur von Mainz (19. Oktober 1792)",
      "No. 3. General Custine's first summons to the governor of Mainz (19 October 1792)",
      """Herr General!
Die Truppen die Sie unter sich haben, können Ihre Stadt vom Untergang nicht retten. Was für Vorwürfe hätten Sie sich nicht zu machen! Herr General! wenn Sie an der Wuth Ihres Kurfürsten Theil nehmen, und die Stadt die Ihnen anvertraut ist, dem Greuel eines gewaltsamen Angriffs aussetzten, Sie müßten dafür haften, mit Ihrem Kopf.
Die Franzosen über die ich das Kommando führe, haben in Speier gezeigt, was sie vermögen; wenn ich zu ihnen rede, oder ihnen befehle, dann ist nichts im Stande, ihren Muth zu erschüttern. Zaudern Sie nicht, dann ich warne Sie, wenige Augenblicke sind Ihnen noch übrig, benutzen Sie diese nicht, dann ist morgen keine Zeit mehr, eine reiche und glückliche Stadt wird zum Steinhaufen gemacht.
Sie haben die Wahl, ob Sie die Verwüstung vorziehen, oder die Verbrüderung annehmen wollen, die wir ihnen anbiethen; eine große Schaar tapferer Kriegsmänner wird Ihre Stadt der ohnmächtigen Wuth der verschwornen Despoten zu entreissen wissen, die da glaubten, daß sie nichts als mit dem Tode ringende Menschen in Frankreich zurückgelassen hätten; ihre Armeen sind zu Grunde gerichtet (*) sie wußten nicht, was es hieße, ein freyes Volk zu bekriegen. Nehmen Sie Antheil an dieser unserer Freyheit, Ihre Waffenbrüder haben schon unser Verfahren kennen gelernt, welches wir jeder Nation angedeyen lassen, die sich zu unserem Zwecke vereinigt. Ich erwarte Ihre Antwort und nehme keine Bedenkzeit an.
Französischer Bürger und General
Cüstine.
(*) Sehr viel gesagt, und doch hat eine der zu Grund gerichteten Armeen, nemlich die Preussische, den General Cüstine in seinen weiteren Fortschritten gehindert und denselben sogar zum Rückzuge genöthiget. Kann das wohl eine zu Grund gerichtete Armee seyn?? —""",
      """General!
The troops under your command cannot save your city from ruin. What reproaches would you not have to make yourself, General, if you take part in the fury of your Elector and expose the city entrusted to you to the horror of an assault! You would have to answer for it with your head.
The Frenchmen whom I command have shown at Speyer what they can do; when I speak to them or command them, nothing can shake their courage. Do not hesitate, for I warn you: only a few moments are left to you. If you do not use them, tomorrow there will be no more time, and a rich and happy city will be made a heap of stones.
You have the choice whether you prefer devastation or will accept the fraternity we offer you. A great host of brave soldiers will know how to snatch your city from the impotent fury of the conspiring despots, who believed they had left nothing in France but men in their death agony; their armies are ruined (*). They did not know what it meant to make war on a free people. Take part in this our liberty; your brothers in arms have already come to know the treatment we grant to every nation that joins our cause. I await your answer and accept no time for reflection.
French citizen and general
Custine.
(*) A great deal said; and yet one of the ruined armies, namely the Prussian, has stopped General Custine in his further progress and even forced him to retreat. Can that be a ruined army?? —""",
      "Die Anmerkung (*) ist Hoffmanns, geschrieben im Frühjahr 1793, als die Preußen Custine schon zurückgedrängt hatten. „dann“ steht im Druck für „denn“. Custine schreibt an den Gouverneur, Freiherrn von Gymnich; die Anrede wechselt zwischen „Herr General“ und, im nächsten Brief, „Herr Commandant“ und „Herr Gouverneur“. Die französische Fassung der Briefe ist hier nicht abgedruckt; Hoffmann gibt die deutsche, die in Mainz umlief.",
      "The note (*) is Hoffmann's, written in spring 1793 when the Prussians had already pushed Custine back. 'dann' stands in the print for 'denn' ('for'). Custine writes to the governor, Freiherr von Gymnich; the address shifts between 'General' and, in the next letter, 'Commandant' and 'Governor'. The French text of the letters is not printed here; Hoffmann gives the German version that circulated in Mainz."),
    u(5, "73–74", "No. 4. Zweyter Brief des General Cüstine an den Gouverneur von Mainz (20. Oktober 1792)",
      "No. 4. General Custine's second letter to the governor of Mainz (20 October 1792)",
      """Herr Commandant!
Mein Verlangen, Menschenblut zu schonen, ist so groß, daß ich mit Vergnügen Ihrem geäusserten Wunsche nachgeben möchte, einen Aufschub bis morgen zu ertheilen, um dann Ihre Antwort zu erhalten; aber, Herr Gouverneur, die Wuth meiner Grenadiere ist so beschaffen, daß ich nicht im Stande bin, sie im Zaum zu halten; sie sehen auf nichts, als auf den Ruhm, die Feinde der Freyheit zu bekämpfen, und auf die reiche Plünderung, die der Lohn ihrer Tapferkeit seyn soll, denn, ich sage es Ihnen voraus, es ist keine regelmäßige Attaque, die Sie zu erwarten haben, sondern eine Attaque mit Sturm.
Ein solcher Angriff ist nicht allein möglich, sondern es ist auch keine Gefahr damit verbunden. Ich kenne so gut Ihre Festung, wie Sie, und die Art von Truppen, die sie vertheidigen sollen. Schonen Sie das Blut so vieler unschuldigen Schlachtopfer von so vielen tausend Menschen, unser Leben ist ohne Zweifel für uns nichts, gewohnt es in den Schlachten auf die Spitze zu bieten, wissen wir es ruhig zu verlieren; aber dann mögen auch jene hochmüthigen Leute, die sich weigerten der Menschlichkeit ein Opfer zu bringen, eingedenk seyn, daß keiner von ihnen davon kommen wird. Die Ehre der Republik, die die Ohnmacht jener Tyrannen benutzte, welche sie unterdrücken wollten, aber die doch für der Fahne der Freyheit fliehen mußten, bin ich es schuldig, daß ich die Wuth meiner tapfern Soldaten nicht bezähmen darf, ja wenn ich es auch wollte, meine Bemühung wäre vergebens. Antwort, Antwort, Herr Gouverneur!
Franken Bürger und General der Armee
Cüstine.""",
      """Commandant!
My desire to spare human blood is so great that I should gladly grant your expressed wish for a delay until tomorrow, so as to receive your answer then; but, Governor, the fury of my grenadiers is such that I am not able to hold them in check. They look to nothing but the glory of fighting the enemies of liberty and to the rich plunder that is to be the reward of their bravery; for, I tell you beforehand, it is not a regular attack you have to expect but an attack by storm.
Such an assault is not only possible, it carries no danger with it. I know your fortress as well as you do, and the kind of troops who are to defend it. Spare the blood of so many innocent victims, of so many thousands of people. Our own lives are no doubt nothing to us; used to staking them in battle, we know how to lose them calmly. But then let those haughty people who refused to make a sacrifice to humanity remember that not one of them will escape. To the honour of the Republic, which took advantage of the impotence of the tyrants who wanted to oppress it but had to flee before the banner of liberty, I owe it not to tame the fury of my brave soldiers; and even if I wished to, my efforts would be in vain. An answer, an answer, Governor!
Citizen of the Franks and general of the army
Custine.""",
      "Gymnich hatte um Aufschub bis zum nächsten Morgen gebeten. Hoffmann hält die Drohung für leer: Custine sei „kein Laudon“, der eine Festung stürme, bevor er sie mit Feuer angegriffen habe (Heft 1, S. 58, Anm.). „Für der Fahne“ steht im Druck für „vor der Fahne“. „Franken Bürger“: Die Revolution nannte die Franzosen gern „Franken“, ihre Republik die „Frankenrepublik“; Hoffmann spottet über die „Neufranken“.",
      "Gymnich had asked for a delay until the next morning. Hoffmann thinks the threat empty: Custine was 'no Laudon', who would storm a fortress before attacking it with fire (Heft 1, p. 58, note). 'für der Fahne' in the print stands for 'vor der Fahne' ('before the banner'). 'Citizen of the Franks': the Revolution liked to call the French 'Franks' and their republic the 'Republic of the Franks'; Hoffmann mocks the 'New Franks'."),
    u(6, "74–75", "No. 5. Andere Aufforderung des Generals Cüstine an den Burgermagistrath zu Mainz (20. Oktober 1792)",
      "No. 5. General Custine's other summons to the city magistrate of Mainz (20 October 1792)",
      """Vorsteher des Volks!
Vom Volke gewählt, von ihm auserkohren, sein Glück zu befördern — was kann euch theurer, was euch mehr angelegner seyn, als von ihm die Greuel des Krieges und die unvermeidliche Verheerungen einer mit gewaltsamer Hand gemachten Eroberung abzuwenden. Alle Mittel stehen mir zu Befehle, Eure Stadt in Asche zu verwandeln, Röste zu Verfertigung feuriger Kugeln, Haubitzen und entzündendes Feuerwerk. Ihr kennt den Grad der Vollkommenheit unsrer Artillerie, sie erschreckte, beschwichtigte unsere hochmüthigen Feinde, sie vereitelte ihre hochfliegenden Plane, genährt durch die strafbare Intrigue unserer alten Minister.
Euer Kurfürst war Theilnehmer ihrer Wuth; die Frankenrepublik aber wird nach ihrer Gerechtigkeit den Wunsch des friedlichen Bürgers von den hirnlosen Projekten Eures Kurfürsten zu unterscheiden wissen! — Gebt uns Beweise Eurer brüderlichen Einigkeit, öffnet uns die Thore und rechnet auf die brüderliche Behandlung, die ich euch anbiete.
Eine zahlreiche Besatzung tapferer Vertheidiger, eine ganze Armee zu ihrer Unterstützung werden euch mit gewaltiger Hand gegen die Drohungen verschworner Despoten in Sicherheit setzen.
Ihr kennt vielleicht heute schon die traurige Lage, in welche ihre Wuth sie stürzte, ihre Armeen fliehen aufgescheucht vor den Fahnen der Freyheit her; ohne Gefahr könnt ihr den Ruhm theilen, den unsre kraftvolle Entschliessung euch zusichert.
Aber hört es, Räthe des Volks! wenn ihr mich zwingt, das schreckliche Mittel des Krieges anzuwenden, wenn Eure Bürger sich als unsere Feinde erklären, so schreibt Euch selbst zu die Greuel des Plünderns und die gänzliche Einäscherung eurer Stadt.
Ihr kennt der Franken streitbare Männer; die, denen ich befehle, hören meine Stimme, ein alter Krieger führt sie an, nichts ist ihnen unter seinen Befehlen unmöglich.
Die Anstalten zu eurer Zerstörung sind bereit, der morgende Tag ist der letzte Eures Daseyns. Ich kündige euch nichts an, das nicht geschehen wird, ich betrüge euch nicht. Noch wenige Stunden habt ihr Zeit, bedenkt euch, handelt! —
Der Franken Bürger und General der Armeen.
Cüstine.""",
      """Leaders of the people!
Elected by the people, chosen by it to further its happiness — what can be dearer to you, what of more concern to you, than to turn from it the horrors of war and the unavoidable devastation of a conquest made by force? Every means of turning your city to ashes is at my command: grates for making red-hot shot, howitzers and incendiary fireworks. You know the perfection of our artillery: it terrified and quieted our haughty enemies, it frustrated their high-flown plans, fed by the criminal intrigue of our former ministers.
Your Elector shared in their fury; but the Republic of the Franks, in its justice, will know how to distinguish the wish of the peaceful citizen from the brainless projects of your Elector! — Give us proof of your brotherly unity, open the gates to us, and count on the brotherly treatment I offer you.
A numerous garrison of brave defenders, a whole army to support them, will with a mighty hand make you safe against the threats of conspiring despots.
Perhaps you already know today the sad state into which their fury has thrown them: their armies flee, scattered, before the banners of liberty. Without danger you may share the glory that our vigorous resolution assures you.
But hear this, councillors of the people! If you force me to use the terrible means of war, if your citizens declare themselves our enemies, then you have only yourselves to blame for the horrors of plunder and the complete burning of your city.
You know the fighting men of the Franks; those whom I command hear my voice; an old soldier leads them; nothing is impossible to them under his orders.
The preparations for your destruction are ready; tomorrow is the last day of your existence. I announce nothing to you that will not happen; I do not deceive you. You have a few hours yet: think, act! —
Citizen of the Franks and general of the armies.
Custine.""",
      "Der Brief ist an den Stadtrat gerichtet, nicht an den Gouverneur, und zieht eine Linie, die das ganze Jahr bestimmen wird: hier der „friedliche Bürger“, dort die „hirnlosen Projekte Eures Kurfürsten“. Der Magistrat hat ihn nach Hoffmann nie erhalten (siehe [10]). Der Mainzer Stadtrat wurde 1792 nicht gewählt, sondern vom Kurfürsten eingesetzt; Custines Anrede „Vom Volke gewählt“ ist Rhetorik, oder eine Aufforderung.",
      "The letter is addressed to the city council, not to the governor, and draws a line that will shape the whole year: on one side the 'peaceful citizen', on the other 'the brainless projects of your Elector'. According to Hoffmann, the magistrate never received it (see [10]). In 1792 the Mainz city council was not elected but appointed by the Elector; Custine's 'elected by the people' is rhetoric, or an invitation."),
]

UEBERGABE = [
    u(7, "76–77", "No. 6. Brief des Kommandanten von Gymnich an den General Cüstine (20. Oktober 1792)",
      "No. 6. Letter of the commandant von Gymnich to General Custine (20 October 1792)",
      """Herr General!
Wenn ich die Ehre hätte, von Ihnen persönlich gekannt zu seyn, so bin ich überzeugt, Herr General, daß sie nicht zu den Mitteln der Drohung gegriffen hätten, um mich zur Uebergabe einer Festung zu überreden, von der ich Kommandant bin. Ich bin Officier, Herr General, sie kennen das Wort auch, und ich fürchte den Tod nicht, wenn ich meine Pflicht erfülle.
Der Antheil den ich an dem Wohl meiner Mitbürger nehme, und das Verlangen, welches ich trage, ihnen den Greuel eines Bombardements zu ersparen, sind es, die mich bewegen. Ich habe volle Gewalt von meinem Fürsten, Ihnen die Stadt und Festung Mainz unter nachstehenden Bedingnissen zu übergeben.
1) Die Mainzer Garnison mit allen ihren Hülfstruppen ohne Ausnahme, kann frey und mit den Ehrenzeichen des Krieges abziehen, sie kann sich hinbegeben, wohin sie will, und zugleich überläßt man es ihr, selbst die nöthige Mittel zu errichten, um ihre Kriegskasse, Artillerie, Effecten und Bagage fortzuschaffen.
2) Das Ministerium, die Dikasterien, und alle Personen, die in Diensten Ihrer kurfürstlichen Gnaden standen, wie auch die hohe und niedere Geistlichkeit, dürfen mit ihren Effecten auswandern. Jeder Einwohner der Stadt Mainz, er sey gegenwärtig oder nicht, genießt die nemliche Freyheit, und jedem Bürger wird man sein Eigenthum ohne gekränkt lassen.
3) Obgleich mein Fürst in keinen Krieg mit Frankreich verwickelt war, so ist er doch bereit keinen Antheil je daran zu nehmen, er hoffet daher, daß man sein Eigenthum und seine Besitzungen schonen werde.
4) Nach Unterzeichnung dieser Capitulation wird alle Feindseeligkeit aufhören, man wird von beyden Seiten Commissarien ernennen, um den Marsch, Transport, und alles was dahin einschlägt, zu reguliren.
Herr General ich habe die Ehre zu seyn Ihr gehorsamster und ganz ergebener Diener
B. von Gymnich, Gouverneur von Mainz.""",
      """General!
If I had the honour of being known to you personally, I am convinced, General, that you would not have resorted to threats to persuade me to surrender a fortress of which I am commandant. I am an officer, General; you know the word too; and I do not fear death when I do my duty.
It is the concern I feel for the welfare of my fellow citizens, and my wish to spare them the horror of a bombardment, that move me. I have full power from my prince to surrender to you the city and fortress of Mainz on the following conditions.
1) The Mainz garrison with all its auxiliary troops, without exception, may march out freely with the honours of war and go wherever it wishes, and it is left to it to provide the necessary means to carry off its war chest, artillery, effects and baggage.
2) The ministry, the government offices and all persons who were in the service of His Electoral Grace, as well as the higher and lower clergy, may leave with their effects. Every inhabitant of the city of Mainz, present or not, enjoys the same freedom, and every citizen's property will be left to him unharmed.
3) Although my prince was not involved in any war with France, he is ready never to take part in it, and he therefore hopes that his property and possessions will be spared.
4) Upon signature of this capitulation all hostilities will cease; commissioners will be named on both sides to regulate the march, the transport and everything that belongs to it.
General, I have the honour to be your most obedient and wholly devoted servant,
B. von Gymnich, Governor of Mainz.""",
      "Rudolph Eickemeyer, Major im Ingenieurkorps, brachte den Brief am Abend des 20. Oktober ins französische Lager (siehe [10]). Bedingung 3 ist bemerkenswert, nachdem Mainzer Truppen drei Wochen zuvor bei Speyer gegen die Franzosen gekämpft hatten (siehe [2]); und sie fehlt in der Kapitulation (siehe [11] und [12]).",
      "Rudolph Eickemeyer, major in the engineer corps, took the letter to the French camp on the evening of 20 October (see [10]). Condition 3 is remarkable, three weeks after Mainz troops had fought the French at Speyer (see [2]); and it is missing from the capitulation (see [11] and [12])."),
    u(8, "77–78", "No. 7. Gymnich an den k. k. Hauptmann Andujar (20. Oktober 1792)",
      "No. 7. Gymnich to the Imperial captain Andujar (20 October 1792)",
      """Nachdem der K. K. Herr Hauptmann Andujar von Joseph Colloredo, mit seiner unterhabenden Mannschaft zur Vertheidigung der Festung Mainz meinem Kommando überlassen worden; da aber dermalen wegen von allen Seiten gesuchten und nicht erhaltenen Sukurses mich genöthigt sehe, mit den französischen Truppen mich in Capitulation einzulassen: so wird dem Herrn Hauptmann angeordnet, hier zu verbleiben, und sich in jenes zu fügen, was die Capitulation mit sich bringen wird, da man ohnehin darauf bedacht ist, selbe so wenig nachtheilig zu machen, als es immer möglich ist. Da nun der Herr Hauptmann der älteste Infanteristen Officier ist, so hat derselbe diesen Befehl den gesammten Herrn bekannt zu machen, welche solchem wie derselbe nachzukommen haben.
Gouverneur von Kur-Mainz, und K. K. Generalmajor
B. von Gymnich.""",
      """Whereas the Imperial and Royal captain Andujar of the Joseph Colloredo regiment, with the men under him, has been placed under my command for the defence of the fortress of Mainz; and whereas I now find myself obliged, for want of the relief sought on all sides and not obtained, to enter into a capitulation with the French troops: the captain is ordered to remain here and to comply with whatever the capitulation brings, since care is being taken in any case to make it as little disadvantageous as at all possible. As the captain is the senior infantry officer, he is to make this order known to all the gentlemen, who are to obey it as he does.
Governor of Electoral Mainz and Imperial and Royal major general
B. von Gymnich.""",
      "Andujar führte kaiserliche Infanterie des Regiments Joseph Colloredo, die kurz vor der Einschließung in die Stadt gekommen war; Hoffmann zählt 821 Mann (Heft 1, S. 40). „K. K.“ heißt kaiserlich-königlich, also österreichisch.",
      "Andujar commanded Imperial infantry of the Joseph Colloredo regiment, which had come into the city shortly before it was invested; Hoffmann counts 821 men (Heft 1, p. 40). 'K. K.' means imperial and royal, that is, Austrian."),
    u(9, "78", "No. 8. Antwort des Hauptmann Andajur an den Kommandanten (20. Oktober, 11 Uhr abends)",
      "No. 8. Captain Andujar's answer to the commandant (20 October, 11 at night)",
      """Nach Erhaltung des von Ew. Excellenz mir ertheilten Befehls habe alsogleich die K. K. Herrn Officiers, die meinem Kommando anvertraut worden sind (während des Waffenstillstandes) zusammen berufen, den Befehl kommunizirt, und selben meine Meinung und festen Entschluß offenbaret, und alle sind der nämlichen Meinung und Entschliessung, sich bis auf den letzten Mann zu vertheidigen, und nie den Franzosen sich zu ergeben.
Wenn also Ew. Excellenz uns unterstützen wollen, so werden wir uns aufs äußerste vertheidigen, wo nicht, so kann ich mich in keine Bedingnissen einlassen, sondern muß es auf's schleunigste Sr. hochfürstlichen Durchlaucht Herrn Feldmarschall, Prinzen zu Nassau-Usingen berichtet werden, unter dessen hohen Befehlen ich stehe, so bald meine Bestimmung hier aufhöret.""",
      """On receiving the order Your Excellency gave me, I at once called together the Imperial and Royal officers entrusted to my command (during the armistice), communicated the order, and told them my opinion and firm resolve; and all are of the same opinion and resolve: to defend ourselves to the last man and never to surrender to the French.
If, then, Your Excellency will support us, we shall defend ourselves to the utmost; if not, I cannot enter into any conditions, but it must be reported with all speed to His Serene Highness the Field Marshal, the Prince of Nassau-Usingen, under whose high command I stand as soon as my assignment here ends.""",
      "Die Schreibung „Andajur“ in der Überschrift wie gedruckt. Die kaiserlichen Truppen zogen am 21. Oktober ohne Kapitulation über die Rheinbrücke ab (siehe [14]); die Kapitulation [12] nennt nur die „mainzischen und Kreistruppen“.",
      "The spelling 'Andajur' in the heading is as printed. The Imperial troops marched off over the Rhine bridge on 21 October without capitulating (see [14]); the capitulation [12] names only 'the Mainz and Circle troops'."),
    u(10, "58–59", "Hoffmann: der Abend des 20. Oktober", "Hoffmann: the evening of 20 October",
      """XIV. Hierauf schickte der Kommandant Abends gegen 6 Uhr den Ingenierobristlieutenant Eikenmayer nebst einem Trompeter mit einem Schreiben von demselben an den General Cüstine, worinn er ihm den Vorschlag zur Kapitulation machte. Dieses Schreiben selbsten ist unter den Beylagen sub No. 6. Den Brief des Generals Cüstine an den Magistrat der Stadt hat man demselben nicht überliefert, und hielt sogar den Entschluß, die Stadt zu übergeben, vor der Bürgerschaft sorgfältig geheim, ja man verboth sogar den wenigen, denen man es gewissen verfassungsmäßigen Verhältnissen gemäß offenbaren mußte, es der Bürgerschaft kund zu machen. Diesem ohngeachtet hatten es einige doch erfahren, worunter vorzüglich Matthias Metternich einer gewesen, der aber auch so unverschämt gewesen war, gleich Abends noch am 20ten eine schon längst geheim gehabte Nationalkokarde von gewebener Wolle aufzustecken.""",
      """XIV. Thereupon, towards six in the evening, the commandant sent the lieutenant colonel of engineers Eickemeyer, with a trumpeter, carrying a letter from him to General Custine in which he proposed a capitulation. This letter itself is among the appendices as No. 6. General Custine's letter to the city magistrate was never delivered to it, and the decision to surrender the city was even carefully kept secret from the citizenry; indeed the few to whom it had to be disclosed under certain constitutional arrangements were forbidden to make it known to the citizens. Some nonetheless found out, among them above all Matthias Metternich, who was even so shameless as to pin on, that same evening of the 20th, a national cockade of woven wool that he had long kept hidden.""",
      "Eickemeyer heißt hier Obristlieutenant, in der Kapitulation Major; beides wie gedruckt. Matthias Metternich, Professor der Mathematik, wurde einer der Wortführer des Klubs und Mitglied des Konvents. Die Kokarde in den Farben der Revolution war das Zeichen, mit dem man sich zur Republik bekannte; am Tag darauf verteilten französische Soldaten sie an Mainzer, die ins Lager liefen (siehe [15]).",
      "Eickemeyer is called lieutenant colonel here and major in the capitulation; both as printed. Matthias Metternich, professor of mathematics, became one of the club's spokesmen and a member of the Convention. The cockade in the colours of the Revolution was the sign by which one professed the Republic; the next day French soldiers handed it out to people from Mainz who ran out to their camp (see [15])."),
    u(11, "156 Anm.", "Hoffmann über Eickemeyer (Heft 2)", "Hoffmann on Eickemeyer (Heft 2)",
      """Man vergleiche im ersten Heft, die pag. 76 befindliche Beylage sub No. 6 mit der pag. 79. befindliche Beylage sub No. 9, sollte hier nicht Eikenmayer selbst Cüstine gerathen haben, den Artikul wegen dem Hofeigenthum nicht einzugehen, ich wenigstens bin versichert, daß Cüstine alles sich hätte gefallen lassen, um nur Eroberer von Mainz zu werden; weil er hierdurch seinen Eigennutz und seinem Ehrgeitz schmeichelte.""",
      """Compare, in the first Heft, appendix No. 6 on p. 76 with appendix No. 9 on p. 79: might not Eickemeyer himself have advised Custine not to accept the article on the court's property? I at least am certain that Custine would have put up with anything just to become the conqueror of Mainz, because it flattered his self-interest and his ambition.""",
      "Die Anmerkung steht in Heft 2 an einer Stelle, wo Hoffmann Gymnich vorwirft, Eickemeyer vertraut zu haben, obwohl dieser „mit den Propagandisten schon längstens verdächtig gewesen“ sei; abgedruckt ist hier nur ihr Anfang. Eickemeyer trat bald darauf in französische Dienste. Der Vergleich, den Hoffmann verlangt, lässt sich hier ziehen: Gymnichs dritte Bedingung [7] fehlt in der Kapitulation [12].",
      "The note stands in Heft 2 at a point where Hoffmann blames Gymnich for trusting Eickemeyer, although he had 'long been suspect with the propagandists'; only its beginning is printed here. Eickemeyer soon entered French service. The comparison Hoffmann asks for can be made here: Gymnich's third condition [7] is missing from the capitulation [12]."),
    u(12, "79–80", "No. 9. Capitulation der Uebergabe (21. Oktober 1792)", "No. 9. Capitulation of the surrender (21 October 1792)",
      """Wir unterzeichnete, Ludwig Dominikus Munier, Feldmarschall de Champ der Armeen der französischen Republick, und Renne Joseph Petigny, Kriegskommissair gedachter Armeen, von Herrn General Cüstine, einer Seits bevollmächtigte, um die Capitulations-Artikel der Stadt Mainz zu reguliren, und Mauriz Kalkhof, kurfürstl. mainzischer Geheimerath, und Rudolph Eikenmayer, Major von dem Geniekorps anderer Seits, von Herrn Gymnich bevollmächtigte, zu besagter Capitulation zu schreiten, haben uns zu diesem Ende vereinigt, und nachstehende Artikel vestgesetzt.
Art. 1. Die Mainzische und sämmtliche Kreißtruppen, die sich hier befinden, ziehen ohne alle Ausnahme frey mit allen Ehrenzeichen des Kriegs, aus der Festung, und können sich hinbegeben, wo es ihnen beliebt. Sie führen mit sich ihre Kriegskasse, Artillerie, Effecten und Bagage; zu diesem Behuf wird man Ihnen alle hiezu erforderliche Passeporten, deren sie benöthiget seyn könnten, ertheilen.
Art. 2. Da die Garnison nur aus vier Bataillons bestehet, so kann dieselbe nicht mehr als vier Feldstücke mit Pferden und nöthigen Munitionswägen mit nehmen, und man wird ihnen zu deren sowohl, als der Equipagtransportirung, die erforderliche Wägen und Schiffe anweisen.
Art. 3. Die besagten mainzer und Kreistruppen verbinden sich, gegen die französische Republik, und gegen ihre Aliirten, ein ganzes Jahr hindurch, von dem heutigen Tage an gerechnet, nicht zu dienen.
Art. 4. Die ganze Artillerie des Platzes, die Plane, die sich auf die Festung beziehenden Schriften, der Mund- und Kriegsvorrath, und andere Militairische Magazine und Einrichtungen, wie sie immer in der Stadt bestehen mögen, bleiben zurück, und die Ueberlieferung davon geschiehet an einen hiezu von dem französischen Herrn General zu bestellenden Commissarius.
Art. 5. Alle Kranken, welche sich in den militairischen Hospitalen befinden, werden auf Kosten ihres Korps fernerhin verpfleget, und nach ihrer Genesung mit den nöthigen Passeporten und Sicherheitsgeleite zu ihrem Korps zurückgesandt werden.
Art. 6. Der französische General wird sogleich nach beyderseitiger Ratifikation das Rhein- und Gauthor mit 2 Kompagnien Grenadier besetzen lassen.
Art. 7. Das Ministerium, die Dikasterialpersonen, der hohe und niedere Klerus, weniger nicht alle dem kurfürstlichen Hofe zugethane Personen, können mit ihren Effekten ungehindert ausziehen, alle Einwohner, Einheimische und Abwesende, geniesen gleiches Recht, und sollen diesfalls auf Verlangen jedem die nöthigen Passeporten und Sicherheitsgeleiten gegeben werden.
Art. 8. Der französische General unterwirft dem Schutze des Gesetzes das Privatvermögen eines jeden einzelnen Einwohners, in Gemäßheit der Grundsätze der französischen Konstitution, und garantirt die sichere Erhaltung derselben.
Geschehen und geschlossen durch uns obbenannte Kommissarien im Lager zu Marienborn bey Mainz, den 21sten Oktober 1792. im ersten Jahr der französischen Republick.
Kalkhof, Kurf. Mainz. Geh. Rath. — Eikenmayer, Ingenieur-Major. — Der Bürger Marschall de Camp. Munnier. — A. R. Petigny, Kriegskommissair.
radifizirt durch mich Kommandanten der Stadt Mainz Gymnich. Mainz den 21. Oct. 1792. — ratifizirt durch mich Bürger, General der französischen Armee. Cüstine. Mainz den 21. Oct. 1792.""",
      """We the undersigned, Louis Dominique Munier, maréchal de camp of the armies of the French Republic, and René Joseph Petigny, war commissary of the said armies, empowered on the one part by General Custine to settle the articles of capitulation of the city of Mainz, and Moritz Kalkhof, Electoral Mainz privy councillor, and Rudolph Eickemeyer, major of the engineer corps, empowered on the other part by Herr Gymnich to proceed to the said capitulation, have met for this purpose and fixed the following articles.
Art. 1. The Mainz troops and all the Circle troops present here march out of the fortress without any exception, freely, with all the honours of war, and may go wherever they please. They take with them their war chest, artillery, effects and baggage; for this purpose they will be given all the passports they may need.
Art. 2. As the garrison consists of only four battalions, it may take no more than four field pieces with horses and the necessary ammunition wagons; and the necessary wagons and boats will be assigned to it for these as well as for the transport of its equipment.
Art. 3. The said Mainz and Circle troops undertake not to serve against the French Republic and its allies for a whole year, counted from today.
Art. 4. All the artillery of the place, the plans, the papers relating to the fortress, the provisions and munitions, and other military magazines and installations, of whatever kind they may be in the city, remain behind, and are handed over to a commissary to be appointed for the purpose by the French general.
Art. 5. All the sick in the military hospitals will continue to be cared for at the expense of their corps and, once recovered, sent back to their corps with the necessary passports and safe-conduct.
Art. 6. Immediately after ratification by both sides the French general will have the Rhine Gate and the Gau Gate occupied by 2 companies of grenadiers.
Art. 7. The ministry, the officials of the government offices, the higher and lower clergy, and no less all persons attached to the Electoral court may leave unhindered with their effects; all inhabitants, resident and absent, enjoy the same right, and the necessary passports and safe-conducts shall be given to each on request.
Art. 8. The French general places the private property of every single inhabitant under the protection of the law, in accordance with the principles of the French constitution, and guarantees its safe keeping.
Done and concluded by us, the above-named commissioners, in the camp at Marienborn near Mainz, 21 October 1792, in the first year of the French Republic.
Kalkhof, Electoral Mainz privy councillor. — Eickemeyer, engineer major. — Citizen maréchal de camp Munnier. — A. R. Petigny, war commissary.
Ratified by me, commandant of the city of Mainz, Gymnich. Mainz, 21 Oct. 1792. — Ratified by me, citizen, general of the French army, Custine. Mainz, 21 Oct. 1792.""",
      "Gymnichs Bedingungen 1, 2 und 4 kehren als Artikel 1, 7 und das Ganze wieder; seine dritte, die Schonung von Eigentum und Besitz des Kurfürsten, fehlt. Artikel 8 schützt nur das Privatvermögen der Einwohner. Was dem Hof und dem Kurstaat gehörte, lag damit in der Hand der Republik. Die Namen schreibt der Druck uneinheitlich (Munier, Munnier; Renne Joseph, A. R. Petigny; radifizirt, ratifizirt); hier wie gedruckt, in der Übersetzung vereinheitlicht. Marienborn liegt auf der Höhe südwestlich der Stadt.",
      "Gymnich's conditions 1, 2 and 4 reappear as articles 1 and 7 and in the whole; his third, the sparing of the Elector's property and possessions, is missing. Article 8 protects only the private property of the inhabitants. What belonged to the court and the Electoral state was thereby in the hands of the Republic. The print spells the names inconsistently (Munier, Munnier; Renne Joseph, A. R. Petigny; radifizirt, ratifizirt); they stand as printed in the original and are standardized in the translation. Marienborn lies on the heights south-west of the city."),
]

EINZUG = [
    u(13, "Vorrede 1–2, 10", "Hoffmann: Vorrede (12. April 1793)", "Hoffmann: preface (12 April 1793)",
      """Die Einnahme der Stadt und Festung Mainz durch die Franzosen war eine für den grösten Theil der Rheingegend äuserst betrübte und für die gegen Frankreich verbundene Mächte äuserst nachtheilige Ereigniß, die zu so mannigfaltigen Sagen und Erzählungen Veranlassung gegeben hat.
Noch auffallender als die Einnahme war einem jeden biedern Teutschen die wenige Zeit nach dem Einmarsch der Franzosen in Mainz aufgetretene Gesellschaft der Freunde von Freiheit und Gleichheit, deren einziger Zweck es war, die alte mit dem teutschen Reich verbundene monarchische Staatsverfassung gewaltsam umzustoßen. Ihr vorgespiegelter Beweggrund war, den in Monarchien eingeschlichenen Menschendruck, der nun ihrem Vorgeben nach, in alles belebende Freiheit und Gleichheit verwandelt werden sollte — Welcher auch nur halb scharfsinnige Menschenverstand erkannte aber nicht gleich ihre eigentliche Absicht, die blos dahin gieng, die Regierungsgewalt an sich zu bringen, und nach erreichtem Zwecke, den grösten Haufen nach ihrer Pfeife tanzen zu lassen. […]
Diese Darstellung aller wichtigen Ereignisse, die einem teutschen Publikum gewiß nicht uninteressant seyn kann, schrieb ich in Mainz mit vieler Mühe und vielen Gefahren, bis auf den Tag meiner Abreise; hinterliße aber einen guten Freund, der mir noch alles sammelt, damit das Werk bis zur wieder hergestellter Ruhe und Ordnung fortgesetzt werden kann. […]
Geschrieben am 12ten April 1793.
Der Verfasser.""",
      """The taking of the city and fortress of Mainz by the French was an event most grievous for the greater part of the Rhineland and most damaging for the powers allied against France, and it has given rise to so many different rumours and tales.
Still more striking than the taking, to every honest German, was the Society of the Friends of Liberty and Equality that appeared a short time after the French marched into Mainz, whose sole purpose was to overthrow by force the old monarchical constitution bound up with the German Empire. Its pretended motive was the oppression of men that had crept into monarchies, which, as they alleged, was now to be turned into all-quickening liberty and equality — but what mind with even half its wits did not see at once their real aim, which went no further than to seize the power of government and, the goal once reached, to make the great mass dance to their pipe? […]
This account of all important events, which cannot fail to interest a German public, I wrote in Mainz with much trouble and many dangers, up to the day of my departure; but I left behind a good friend who is still collecting everything for me, so that the work can be continued until peace and order are restored. […]
Written on 12 April 1793.
The author.""",
      "Die Hefte erschienen anonym; die Bayerische Staatsbibliothek führt sie unter Anton Hoffmann. Die Vorrede umfasst zehn Seiten; abgedruckt sind ihr Anfang (S. 1–2) und ihr Schluss (S. 10). Dazwischen leitet Hoffmann den Klub von den Illuminaten und einer geheimen „Propaganda“ ab, die seit 1786 in Mainz bestanden habe: eine Verschwörungserzählung, die in den Jahren nach 1793 weit verbreitet war. Am 12. April 1793 war die Stadt noch französisch; wenige Tage später schlossen die Belagerer den Ring.",
      "The Hefte appeared anonymously; the Bavarian State Library catalogues them under Anton Hoffmann. The preface runs to ten pages; its beginning (pp. 1–2) and its end (p. 10) are printed here. In between Hoffmann derives the club from the Illuminati and a secret 'Propaganda' said to have existed in Mainz since 1786: a conspiracy story widely spread in the years after 1793. On 12 April 1793 the city was still French; a few days later the besiegers closed the ring."),
    u(14, "63–64", "Die Ratifikation und der Abzug der Kaiserlichen", "The ratification and the departure of the Imperial troops",
      """Erst nach 10 Uhr kamen die Abgeordnete mit der geschlossenen Kapitulation, die unter den Beylagen sub No. 9. sich befindet, welche sodann von dem Kommandanten genehmiget, und durch den Husarenrittmeister Freyherrn von Rüdt in das französische Lager zur gleichmäßigen Ratification geschickt wurde, die auch noch Mittags gegen 3 Uhr erfolgte.
(*) Diese wahrhaft tapfere Krieger, die nur Siegen gewohnt waren, sollten nun eine Festung ohne Noth verlassen, dieses schien ihnen entehrend zu seyn. — Sie schäumten vor Bosheit, daß ihnen ihr Verlangen, sich mit den Franzosen zu messen, durch die Uebergabe der Festung vereitelt worden war. — Diese Festung schien ihnen von Wichtigkeit und einer ausserordentlichen Stärke zu seyn, sie gaben also den auf dem Schloßplatze als den Ort ihrer Versammlung anwesenden Mainzern eine derbe Lektion, daß sie zugegeben hätten, daß man eine solche Festung ohne vorhergegangenen Angriff den Franzosen übergeben. Zu Kriegsgefangenen wollten sie sich weder durch eine Kapitulation, noch sonst auf eine Art ergeben. — Auch sich anheischig zu machen, nicht mehr gegen die Franzosen zu dienen, war unter ihrer Würde und ganz wieder ihre Absicht; sie nahmen noch von denen mit auf dem Wällen gewesenen Bürgern schon verfertigte Patronen zu mehrern hunderten, weil man ihnen solche von Seiten des Gouvernements nicht gestattet hatte, und zogen über die Rheinbrücke ab. Cüstine that ihnen sonach Unrecht, wenn er in seinem Bericht an den Nationalconvent sagt, sie hätten aus Angst und Furcht die Kapitulation nicht abwarten wollen.""",
      """Only after ten o'clock did the deputies come back with the concluded capitulation, which is among the appendices as No. 9; it was then approved by the commandant and sent by the cavalry captain Freiherr von Rüdt to the French camp for ratification in the same way, which followed towards three in the afternoon.
(*) These truly brave soldiers, used only to victory, were now to leave a fortress without need; this seemed to them dishonourable. — They foamed with anger that their wish to measure themselves against the French had been thwarted by the surrender of the fortress. — The fortress seemed to them important and of extraordinary strength, so they gave the people of Mainz present on the palace square, their place of assembly, a rough lesson for having allowed such a fortress to be handed to the French without an attack. They would surrender as prisoners of war neither by a capitulation nor in any other way. — To pledge themselves not to serve against the French any more was beneath their dignity and wholly against their purpose; they even took several hundred cartridges already made from the citizens who had been on the ramparts with them, because the government had not allowed them any, and marched off over the Rhine bridge. Custine therefore did them an injustice when he says in his report to the National Convention that they would not wait for the capitulation out of fear and fright.""",
      "Die Anmerkung (*) gehört zum vorangehenden Satz Hoffmanns über die kaiserlichen Truppen unter Andujar, die vor der Kapitulation abzogen (siehe [9]). Custines Bericht an den Pariser Nationalkonvent ist hier nicht abgedruckt. Die Bürger auf den Wällen hatten sich auf den Aufruf vom 7. Oktober [1] hin bewaffnet.",
      "The note (*) belongs to Hoffmann's preceding sentence about the Imperial troops under Andujar, who left before the capitulation (see [9]). Custine's report to the National Convention in Paris is not printed here. The citizens on the ramparts had armed themselves in answer to the appeal of 7 October [1]."),
    u(15, "64–65", "XVIII. Der 21. Oktober", "XVIII. 21 October",
      """XVIII. Noch am 21ten ganz in der Frühe war die Uebergabe der Festung unter dem Bürgerstand zum großen Theil noch ein Geheimniß, und die meisten Bürger konnten es nicht glauben, bis sie durch den Abmarsch der Kaiserlichen Truppen davon vergewissert worden waren, der gröste Theil war hierüber mißvergnügt, ja untröstlich, viele aber schimpften und ahndeten gar eine Verrätherey und Verkaufung.
Gegen 12 Uhr waren schon mehrere Thore geöffnet, und die Stadteinwohner liefen Haufen weiß in das französische Lager, wo viele von den Freyheitssoldaten Nationalkokarden von gespunnener Wolle erhielten; unter denen hinaus gegangenen waren sehr viele vom Janhagel die die Weinberge der Kurfürstlichen Universität und des St. Victors Stiftes Staaren mäßig plünderten.
Gegen sechs Uhr besetzten zwey Kompagnien französischer Nationalgarden Capitulationsmäßig das Gauthor und die Rheinbrücke, diesen folgte General Cüstine, der seinen Wohnsitz in den Kurfürstlichen Zimmern des Schlosses nahm, und sich bald darnach auf das neue Rathhauß verfügte, wo der Rath, alle Stadtofficire und beynahe der gröste Theil der Bürgerschaft versammelt war. Hier wollte sich Cüstine größer zeigen, als er wirklich war, und versicherte in einer Rede die Bürgerschaft, daß er nur gekommen seye, ihnen, die Freundschaft der französischen Republick anzubieten, es stünde in ihrer unbeschränkten Wahl, entweder bey ihrer alten Verfassung zu bleiben, oder sich selbsten eine neue zu wählen, oder auch die französische Konstitution anzunehmen.""",
      """XVIII. Even early on the 21st the surrender of the fortress was still largely a secret among the burghers, and most of them could not believe it until the departure of the Imperial troops made them sure of it. The greater part were displeased, indeed inconsolable, at this; but many cursed and even suspected treason and a sell-out.
By twelve o'clock several gates were already open, and the townspeople ran out in crowds to the French camp, where many received national cockades of spun wool from the soldiers of liberty; among those who went out were very many of the rabble, who plundered the vineyards of the Electoral university and of the foundation of St. Victor like starlings.
Towards six o'clock two companies of French National Guards occupied the Gau Gate and the Rhine bridge, as the capitulation provided; they were followed by General Custine, who took up residence in the Elector's apartments in the palace and soon afterwards went to the new town hall, where the council, all the city officers and almost the greater part of the citizenry were assembled. Here Custine wanted to appear greater than he really was, and assured the citizens in a speech that he had come only to offer them the friendship of the French Republic: it was entirely their free choice whether to keep their old constitution, or to choose a new one for themselves, or to adopt the French constitution.""",
      "Custines Zusage im Rathaus ist der Satz, an dem das folgende Jahr gemessen wird: freie Wahl zwischen alter Verfassung, neuer Verfassung und französischer Konstitution. Im Dezember 1792 bestimmte der Pariser Nationalkonvent, dass in den besetzten Gebieten die alte Ordnung abzuschaffen sei, und im Februar 1793 durfte nur wählen, wer der Freiheit und Gleichheit schwor (Eid [2]). „Janhagel“: das gemeine Volk, abschätzig. Die Weinlese war im Oktober in vollem Gang.",
      "Custine's promise in the town hall is the sentence by which the following year is measured: a free choice between the old constitution, a new one and the French constitution. In December 1792 the National Convention in Paris decreed that the old order was to be abolished in the occupied territories, and in February 1793 only those who swore to liberty and equality could vote (Eid [2]). 'Janhagel': the common people, disparagingly. The grape harvest was in full swing in October."),
    u(16, "65–66", "Bürger und Einwohner", "Citizens and inhabitants",
      """Etwas später in der Zeit hatte es schon mehrere Leute gegeben, die die französische Verfassung über die Maaßen gelobt, und den Wunsch, auf immer französisch zu bleiben, öffentlich geäußert haben. Dieses waren jedoch keine Bürger, sondern nur Einwohner, deren Betragen mit der Schande ewig gebrandmarkt bleibet, wie es die Folge noch besser zeigen wird; diese Leute suchten auch schon an diesem Abend die Bürger und sonstige gute Stadteinwohner auf die nemliche Ideen zu bringen, aber diesmal war ihre Mühe vergebens, denn ihre alte Verfassung war ihnen noch zu sehr am Herzen gelegen, als daß sie eine neue hätten wünschen sollen oder kennen, besonders wenn diese neue gar eine Republikanische Verfassung gewesen.
Am folgendem Tage (den 22sten) kamen schon einzelne Franzosen in einer Menge in die Stadt, um dieselbe zu besichtigen, die aber gegen die Mittagszeit wieder zurück in ihr Lager kehrten. Nachmittags gegen zwey Uhr kamen ungefähr dreitausend Mann Franzosen näher gegen die Stadt angerückt, die mainzer und teutsche Kraißtruppen versammelten sich aber auf der Eisgrube zum Abmarsch, wo die Einwohner zu tausenden sich hindrangen.""",
      """Somewhat later there were already several people who praised the French constitution beyond measure and publicly expressed the wish to remain French for ever. These, however, were not citizens but only inhabitants, whose conduct remains branded with eternal shame, as what follows will show still better. These people tried that very evening to bring the citizens and other good townspeople round to the same ideas, but this time their trouble was in vain, for their old constitution was still too dear to their hearts for them to wish for a new one, or even know of one, especially if the new one was to be a republican constitution.
The next day (the 22nd) single Frenchmen came into the city in great numbers to look at it, but went back to their camp towards midday. Towards two in the afternoon about three thousand French troops moved closer to the city; the Mainz and German Circle troops, however, assembled on the Eisgrube to march off, where the inhabitants crowded by the thousands.""",
      "Die Unterscheidung ist Hoffmanns schärfste Waffe: „Bürger“ hatten das Bürgerrecht der Stadt, also meist Handwerker und Kaufleute in den Zünften; „Einwohner“ waren alle anderen, darunter die Professoren, Beamten und Zugezogenen, aus denen der Klub vor allem bestand. Die Eisgrube ist eine Straße in der Mainzer Altstadt.",
      "The distinction is Hoffmann's sharpest weapon: 'citizens' (Bürger) held the city's citizenship, mostly craftsmen and merchants in the guilds; 'inhabitants' (Einwohner) were everyone else, including the professors, officials and newcomers who made up most of the club. The Eisgrube is a street in the old town of Mainz."),
]

DATA = {
    "titel": "Custine vor Mainz: Aufforderung und Übergabe (Oktober 1792)",
    "titel_en": "Custine before Mainz: summons and surrender (October 1792)",
    "autor": "Die Kurfürstliche Statthalterschaft, General Custine, Gouverneur von Gymnich und Hauptmann Andujar; gesammelt und erzählt von Anton Hoffmann",
    "autor_en": "The Electoral Lieutenancy, General Custine, Governor von Gymnich and Captain Andujar; collected and narrated by Anton Hoffmann",
    "jahr": "1792/1793",
    "sprache": "de",
    "orig_sprache": "de",
    "pg_label": "S.",
    "quelle": "[Anton Hoffmann], Darstellung der Mainzer Revolution, oder umständliche und freymüthige Erzehlung aller Vorfallenheiten, so sich seit dem entstandenen französischen Revolutionskrieg zugetragen … mit allen nöthigen Beylagen, Heft 1 (Frankfurt und Leipzig 1793), Vorrede S. 1–2, 10, Erzählung S. 58–59, 63–66, Beylagen No. 1–9, S. 67–80; Heft 2 (1793), S. 156 Anm. Gelesen an den Digitalisaten der Bayerischen Staatsbibliothek München (bsb10421482, bsb10421483).",
    "hinweis": "Anton Hoffmann schrieb gegen den Klub und für die alte Ordnung, aber er druckte die Dokumente der anderen Seite vollständig ab, als „Beylagen“ am Ende jedes Hefts; seine eigenen Anmerkungen stehen dabei und sind als solche gekennzeichnet. Dieses Modul folgt den vierzehn Tagen vom Aufruf der Statthalterschaft am 7. Oktober bis zum Abzug der Mainzer Truppen am 22. Oktober 1792. Text nach dem Druck, an den Seitenbildern gelesen: Schreibung, Großschreibung und Zeichensetzung wie gedruckt, ſ als s, Kustoden und Bogensignaturen weggelassen, Silbentrennungen am Zeilenende aufgelöst. Auslassungen sind mit […] bezeichnet. Die englische Übersetzung ist eine eigene Arbeitsübersetzung (CC0); die Seitenzahlen der Hefte laufen durch (Heft 1: S. 1–80, Heft 2: S. 81–160).",
    "hinweis_en": "Anton Hoffmann wrote against the club and for the old order, but he printed the other side's documents in full, as 'appendices' at the end of each Heft; his own notes stand beside them and are marked as his. This module follows the fortnight from the Lieutenancy's appeal of 7 October to the departure of the Mainz troops on 22 October 1792. Text as printed, read against the page images: spelling, capitals and punctuation as in the print, long s as s, catchwords and signatures omitted, line-end hyphenation resolved. Omissions are marked […]. The English translation is my own working translation (CC0); the page numbers of the Hefte run on (Heft 1: pp. 1–80, Heft 2: pp. 81–160).",
    "sections": [
        {"id": "statthalter", "titel": "Die Statthalterschaft", "titel_en": "The Lieutenancy", "zk": "Custine",
         "blurb": "Vor der Einnahme: Die Regierung des geflohenen Kurfürsten ruft die Bürger zu den Waffen, verspricht Renten für Verwundete und Ersatz für Brandschäden und verwarnt die Lesegesellschaft, die französische Zeitungen hält. Hoffmann widerspricht der eigenen Regierung in einer Anmerkung.",
         "blurb_en": "Before the capture: the government of the absent Elector calls the citizens to arms, promises pensions for the wounded and compensation for fire damage, and warns the reading society that takes French newspapers. Hoffmann contradicts his own government in a note.",
         "units": STATTHALTER},
        {"id": "aufforderung", "titel": "Custines Aufforderungen", "titel_en": "Custine's summonses", "zk": "Custine",
         "blurb": "Am 19. und 20. Oktober fordert Custine die Festung auf: zweimal den Gouverneur, einmal den Stadtrat. Er droht mit Sturm, Plünderung und Brand und bietet „Verbrüderung“ an. Die Briefe sind der erste Text der Republik an die Mainzer, und sie sind Drohbriefe.",
         "blurb_en": "On 19 and 20 October Custine summons the fortress: twice the governor, once the city council. He threatens storm, plunder and fire and offers 'fraternity'. The letters are the Republic's first text addressed to the people of Mainz, and they are threats.",
         "units": AUFFORDERUNG},
        {"id": "uebergabe", "titel": "Die Übergabe", "titel_en": "The surrender", "zk": "Custine",
         "blurb": "Gymnich bietet die Übergabe an, die kaiserlichen Offiziere weigern sich, und am 21. Oktober wird im Lager zu Marienborn die Kapitulation geschlossen. Eine Bedingung Gymnichs fehlt im Vertrag; Hoffmann verdächtigt den Unterhändler.",
         "blurb_en": "Gymnich offers to surrender, the Imperial officers refuse, and on 21 October the capitulation is concluded in the camp at Marienborn. One of Gymnich's conditions is missing from the treaty; Hoffmann suspects the negotiator.",
         "units": UEBERGABE},
        {"id": "einzug", "titel": "Der 21. Oktober", "titel_en": "21 October", "zk": "Custine",
         "blurb": "Hoffmann erzählt den Tag der Übergabe: Abzug der Kaiserlichen, offene Tore, Kokarden, Custine im Schloss und im Rathaus, wo er den Mainzern die freie Wahl ihrer Verfassung verspricht. Davor seine Vorrede, aus der man erfährt, wer hier schreibt.",
         "blurb_en": "Hoffmann narrates the day of the surrender: the Imperial troops leave, the gates open, cockades are handed out, Custine moves into the palace and goes to the town hall, where he promises the people of Mainz a free choice of their constitution. Before it, his preface, which tells who is writing here.",
         "units": EINZUG},
    ],
}

if __name__ == "__main__":
    ns = [x["n"] for s in DATA["sections"] for x in s["units"]]
    assert ns == list(range(1, len(ns) + 1)), ns
    OUT.write_text(json.dumps(DATA, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print("ok", OUT.name, len(ns), "units")
